String s = "<position lat=\"59.3252414125\" long=\"18.0750236375\" accuracy=\"1000\"></position>";
    InputSource is = new InputSource(new StringReader(s));
    DOMParser dp = new DOMParser();
    dp.parse(is);
    Document doc = dp.getDocument();
    NodeList nl = doc.getElementsByTagName("position");
    Node n = nl.item(0);
    NamedNodeMap nnm = n.getAttributes();
    String lat = nnm.getNamedItem("lat").getFirstChild().getTextContent();
    String longg = nnm.getNamedItem("long").getFirstChild().getTextContent();
    String accuracy = nnm.getNamedItem("accuracy").getFirstChild().getTextContent();