...
<h:dataTable value="#{myBean.users}" var="user">
    ...
    <h:column>
        <h:commandLink rendered=#{user.connected} value="#{user.id}"/>
        <h:outputText rendered=#{!user.connected} value="#{user.id}"/>
    </h:column>
    ...
</h:dataTable>
...