{
        "Data":[
             {
                "user":1,
                "items":
                      [{"item":1},{"item":2},{"item":3},{"item":4}]
             },
             {
                "user":2,
                "items":
                      [{"item":11},{"item":2},{"item":3},{"item":4}]
             },
            {
               "user":3,
                "items":
                      [{"item":11},{"item":2},{"item":3},{"item":4}]
             }
             ]
}