Scanner sc = new Scanner(System.in);
   ....
   .....
   replaceStr(Scanner sc, String str);
   .....
   ....
   removeNextChars(Scanner sc ,String str);
   ....
   ....
   //In the end
   sc.close();


static void replaceStr(Scanner in, String str){
  //All the code without scanner instantiation and closing
  ...
}

static void removeNextChars(Scanner in, String str){
  //All the code without scanner instantiation and closing
  ...
}