public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int col) {
    ...
    if ("Error" == type) { // This should be "Error".equals(type)
        ...
    }
    ...
}