int connectedClientCount = 0;
// ...
while(true) {
    ServerSocket ss = ...
    Socket s = ss.accept();
    if(connectedClientCount == 2) {
        // Do stuff to tell connected Client that he is rejected because of max clients...
    } else {
        connectedClientCount++;
        // cool stuff...
    }
}