List<Prices> priceList = new ArrayList<Prices>();
        Prices p1 = new Prices(BigDecimal.valueOf(1.2), BigDecimal.valueOf(5.1));
        Prices p2 = new Prices(BigDecimal.valueOf(3.2), BigDecimal.valueOf(4.2));
        Prices p3 = new Prices(BigDecimal.valueOf(1.4), BigDecimal.valueOf(1.4));
        Prices p4 = new Prices(BigDecimal.valueOf(1.3), BigDecimal.valueOf(1.1));
        priceList.add(p1);
        priceList.add(p2);
        priceList.add(p3);
        priceList.add(p4);
        System.out.println(priceList);
        PriceComparator priceComparator = new PriceComparator();
        priceList.remove(priceComparator.getLeastPrice2(priceList));
        System.out.println(priceList);
        Collections.sort(priceList, priceComparator);
        System.out.println(priceList);