@FXML
private void handlePanelButtonAction(ActionEvent event) throws IOException {
    if(event.getSource() == trackerButton) {
        ...
    } else if(event.getSource() == progressButton) {
        ...
    } else if(event.getSource() == communityButton) {
        ...
    } else if(event.getSource() == blockerButton) {
        ...
    } else if(event.getSource() == settingsButton) {
        ...
    } else if(event.getSource() == logoutButton) {
        ...
    }
}