public CSVParser(final Reader reader, final CSVFormat format, final long characterOffset, final long recordNumber)
        throws IOException {
    ...
    this.lexer = new Lexer(format, new ExtendedBufferedReader(reader));
    ...
}