spring.mail.host = smtp.gmail.com
spring.mail.port= 465
spring.mail.username = yottiallipierre@gmail.com
spring.mail.password = losangeles4004*
send.from.email= yottiallipierre@gmail.com
spring.mail.properties.mail.smtp.auth = true;
spring.mail.properties.mail.smtp.starttls.enable = true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.enable = true
spring.mail.properties.mail.socketFactory.port=587
spring.mail.properties.mail.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.socketFactory.fallback=false