SparseArray<String> menuMap = new SparseArray<>();
menuMap.put(0, "1carril");
menuMap.put(1, "2carril");
menuMap.put(2, "3carril");
menuMap.put(3, "abierta1");
menuMap.put(4, "abierta2");
menuMap.put(5, "abierta3");
menuMap.put(6, "abierta4");
menuMap.put(7, "abierta5");
menuMap.put(8, "carril1");
menuMap.put(9, "carril2");
menuMap.put(10, "carril3");