package it.jack.fdd.domain;
// Generated 30-nov-2016 0.17.09 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BankAccount generated by hbm2java
 */
@Entity
@Table(name = "bank_account", catalog = "fdd_dbproducts")
public class BankAccount implements java.io.Serializable {

 private Integer idbankAccount;
 private User user;
 private String iban;
 private String pin;
 private String society;
 private Date expiration;

 public BankAccount() {
 }

 public BankAccount(User user, String iban, String pin, String society) {
  this.user = user;
  this.iban = iban;
  this.pin = pin;
  this.society = society;
 }

 public BankAccount(User user, String iban, String pin, String society, Date expiration) {
  this.user = user;
  this.iban = iban;
  this.pin = pin;
  this.society = society;
  this.expiration = expiration;
 }

 @Id
 @GeneratedValue(strategy = IDENTITY)

 @Column(name = "idbank_account", unique = true, nullable = false)
 public Integer getIdbankAccount() {
  return this.idbankAccount;
 }

 public void setIdbankAccount(Integer idbankAccount) {
  this.idbankAccount = idbankAccount;
 }

 @ManyToOne(fetch = FetchType.EAGER)
 @JoinColumn(name = "fkuser_baccount", nullable = false)
 public User getUser() {
  return this.user;
 }

 public void setUser(User user) {
  this.user = user;
 }

 @Column(name = "iban", nullable = false, length = 45)
 public String getIban() {
  return this.iban;
 }

 public void setIban(String iban) {
  this.iban = iban;
 }

 @Column(name = "pin", nullable = false, length = 45)
 public String getPin() {
  return this.pin;
 }

 public void setPin(String pin) {
  this.pin = pin;
 }

 @Column(name = "society", nullable = false, length = 45)
 public String getSociety() {
  return this.society;
 }

 public void setSociety(String society) {
  this.society = society;
 }

 @Temporal(TemporalType.DATE)
 @Column(name = "expiration", length = 10)
 public Date getExpiration() {
  return this.expiration;
 }

 public void setExpiration(Date expiration) {
  this.expiration = expiration;
 }

}