SELECT GIG.GIG_DESCRIPTION, VENUES.VENUE_NAME, BAND.BAND_NAME, 
CASE WHEN GIG.USERID = 0 THEN '--CREATED BY THE BAND--' ELSE
USERS.USERNAME END, 
GIG.GIG_DATE 
from GIG 
INNER JOIN VENUES ON GIG.VENUEID = VENUES.VENUEID 
INNER JOIN BAND ON GIG.BANDID = BAND.BANDID 
LEFT JOIN USERS ON GIG.USERID = USERS.USERID 
WHERE GIG.GIGID=" + gigID;