sql.selectDistinct(COMPANY.NAME, COMPANY_CONTACT.NAME.as("CONTACT_INTERACTION"))
   .on(COMPANY.COMPANY_ID)
   .from(COMPANY)
   .join(COMPANY_CONTACT)
   .on(COMPANY_CONTACT.COMPANY_ID.eq(COMPANY.ID))
   .where(not(COMPANY.DELETED))
   .orderBy(COMPANY.COMPANY_ID, COMPANY_CONTACT.FOLLOW_UP.desc())
   .fetch();