String s = "I wrote a ";
int i = 4;
double j = 7.0; 
Scanner scan = new Scanner(System.in);
String c; int a; double b;
a = scan.nextInt();
b = scan.nextDouble();
scan.nextLine();
c = scan.nextLine();
System.out.println(i + a);
System.out.println(j + b);
System.out.println(s + c);
scan.close();