from("direct:myRoute")
...
    .setProperty("newItem").simple("${body}")
    .setProperty("name").jsonpath("$.name")
    .setProperty("brand").jsonpath("$.brand")
    .setBody().simple("{'name':'${property.name}','brand':'${property.brand}'}")
    .convertBodyTo(String.class)
    .to("mongodb:mongoBean?database={{db}}&collection= 
         {{col}}&operation=findOneByQuery")
...