....
setContentView(R.layout.main);
....
final ViewGroup locationForMyPreview = (ViewGroup) findViewById(R.id.preview_location);
mPreview = new Preview(this);
locationForMyPreview.addView(mPreview);
....