while (rs.next()){    
                ...    
                    if (userLocation == roomid){
                           ...    
                                 do{
                                 ...
                                 } while (rs.next());
                    }