float x[N],y[N]; // point coordinates as x1,y1   x2,y2 ....
...
  ...
  ...
...
float sum_but_no_result=0;

for(int i=0;i<(N-1);i++) // N is point number of polygon
{
      sum_but_no_result+=x[i]*y[i+1] + y[i]*x[i+1];
}
sum_but_no_result+=x[N-1]*y[0] + y[N-1]*x[0];

float sum= (float)Math.abs(sum_but_no_result) / 2.0f;