animation3 = new AlphaAnimation(0.0f, 1.0f);
    animation3.setFillAfter(true);
    animation3.setDuration(1200);
    mLinear.startAnimation(animation3);
    mText.setText("Meetutu");
    mText1.setText("The joy of meeting an expert teacher");
    mText2.setText("for a craving learner");
         animation = AnimationUtils.loadAnimation(Full_XML_Practise.this, R.anim.move_to_up);
    mText.startAnimation(animation);
    animation1 = AnimationUtils.loadAnimation(Full_XML_Practise.this, R.anim.move_to_down);
    mText1.startAnimation(animation1);
    animation2 = AnimationUtils.loadAnimation(Full_XML_Practise.this, R.anim.move_to_down_slow);
    mText2.startAnimation(animation2);
    animation4 = AnimationUtils.loadAnimation(this, R.anim.zoom_in);
    mButton.startAnimation(animation4);