CREATE TABLE plants (
   id BIGINT NOT NULL PRIMARY KEY,
   plantname VARCHAR(255) NOT NULL,
);

CREATE TABLE plantparts (
   id BIGINT NOT NULL PRIMARY KEY,
   leaves VARCHAR(255) NOT NULL,
   pedicles VARCHAR(255) NOT NULL,
   petals VARCHAR(255) NOT NULL,
   plantid BIGINT NOT NULL,
   FOREIGN KEY (plantid) REFERENCES plants(id)
);