/** Example class delegating to a contained variable */
public class DelegatingComparator implements Comparator<String> {
    // Delegatee has to be present before letting Eclipse generate
    private Comparator<String> delegatee;

    /** My own method extends Comparator methods */
    public int compareToFoo(String o1) {
        return compare(o1, "foo");
    }

    /** Generated by Eclipse. Source > Generate getters and setters */
    public void setDelegatee(Comparator<String> delegatee) {
        this.delegatee = delegatee;
    }

    /** Generated by Eclipse. Source > Generate Delegate Methods */
    public int compare(String o1, String o2) {
        return delegatee.compare(o1, o2);
    }

    /** Generated by Eclipse. Source > Generate Delegate Methods */
    public boolean equals(Object obj) {
        return delegatee.equals(obj);
    }

}