public void performExecute() throws ECException {
        //do something here...
        //....................
        TypedProperty rspProp = new TypedProperty();
        rspProp.put(ECConstants.EC_URL, "YourViewName");
        rspProp.put(ECConstants.EC_VIEWTASKNAME, ECConstants.EC_GENERIC_REDIRECTVIEW);
        //....................
        //....................
    }