{
   "sleep":{
      "userInfo":{
         "firstName":"Hans",
         "lastName":"Schmidt",
         "country":"Germany",
         "city":"Berlin"
      },
      "settings":{
         "setting2":"none",
         "setting1":"y"
      },
      "program":{
         "appVersion":"1.7",
         "serverVersion":19,
         "appName":"name"
      },
      "userType":"new"
   }
}