from(INPUT_SERVICE_ENDPOINT_URI)
        .wireTap(SAVE_COPY_OF_INPUT)
        .unmarshal(jaxbFormat)
        .process(createAuditRecord())
        .bean(webServiceValidator)
        .process(updateAuditRecord())
        .split(body())
            .choice()
                .when(simple("${body.second.rejected}"))
                    .log(LoggingLevel.DEBUG, LOGGER_NAME, "Skipping import as it was rejected")
                .otherwise()
                    .to(ExchangePattern.InOnly, IMPORT_QUEUE_ENDPOINT_URI)
                .endChoice()
            .end()
        .end()
        .process(createWebServiceResponse())
        .marshal(jaxbFormat);