CREATE SEQUENCE sample_sequence;
CREATE TABLE sample_table 
( 
  hash  VARCHAR(20), 
  id    INTEGER generated by default as sequence sample_sequence, 
  data  VARCHAR(256), 
  PRIMARY KEY(hash, id) 
);