final List<Number> myNumbers = ...
Runnable myRunnable = new Runnable() {
    public void run() {
        ...
        myNumbers.add(partialResult);
        if (iAmTheLastRunStanding()) {
            aggregateAndOutput(myNumbers);
        }
    }
}
...
myRunnable.run();
...
myRunnable.run();
...