final JFrame  frame  = new JFrame();
        JPanel panel  = new JPanel();
        JLabel label = new JLabel("രാകേഷ്");
        JLabel label1 = new JLabel("Rakesh");
        JLabel label2 = new JLabel("\u0d30\u0d3e\u0d15\u0d47\u0d37\u0d4d");
        JLabel label3 = new JLabel("Rakesh");
        Font font = new Font("Arial Unicode MS", Font.PLAIN, 12);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        label.setFont(font);
        label1.setFont(font);
        label2.setFont(font);
        label3.setFont(font);
        panel.add(label);
        panel.add(label1);
        panel.add(label2);
        panel.add(label3);
        frame.add(panel);
        frame.setSize(300,300);
        frame.setVisible(true);
        frame.pack();