@Mapper
public interface ReproMapper {

    @Mapping(target = "nested",source = "source")
    @Mapping(target = "anotherId",source = "source.anotherId")
    Repro.TargetEntity fromSource(Repro.SourceEntity source, @Context String externalId);

    //A default impl that delegates to MapStruct generated method
    default Repro.TargetEntity.Nested resolveNested(Repro.SourceEntity source, @Context String externalId) {
        return delegate(source, externalId);
    }

    //Actual Mapping method, generated by MapStruct
    //Note here externalId is not @Context annotated
    @Mapping(target = "version", ignore = true)
    @Mapping(target = "id", source = "source.id")
    @Mapping(target = "externalId", source = "externalId")
    Repro.TargetEntity.Nested delegate(Repro.SourceEntity source, String externalId)

    @Mapping(source = "nested.id", target = "id")
    @Mapping(source = "anotherId", target = "anotherId")
    Repro.SourceEntity fromTarget(Repro.TargetEntity target);
}