List<String> testdata = new ArrayList<>();
testdata.add("1380");
testdata.add("Rio");
testdata.add("Rancho");
testdata.add("Blvd");
testdata.add("SE363");
Log.e("!@#", String.valueOf(checkLineForAddress(testdata)));
testdata = new ArrayList<>();
testdata.add("Rio");
testdata.add("Rancho");
testdata.add("NM");
testdata.add("87124");
Log.e("!@#", String.valueOf(checkLineForAddress(testdata)));
testdata = new ArrayList<>();
testdata.add("Wayne");
testdata.add("Stansfield");
testdata.add("i");
testdata.add("CLCS");
Log.e("!@#", String.valueOf(checkLineForAddress(testdata)));
testdata = new ArrayList<>();
testdata.add("James");
testdata.add("Gordon");
testdata.add("Smith");
Log.e("!@#", String.valueOf(checkLineForAddress(testdata)));
testdata = new ArrayList<>();
testdata.add("5052");
testdata.add("554");
testdata.add("11500");
testdata.add("121151");
Log.e("!@#", String.valueOf(checkLineForAddress(testdata)));
testdata = new ArrayList<>();
testdata.add("Creative");
testdata.add("Director");
Log.e("!@#", String.valueOf(checkLineForAddress(testdata)));