public static void makeGrey(File image) { 
try{
    //Read in original image. 
    BufferedImage inputImage = ImageIO.read(image);
    ...
    ...
    //Save new greyscale (output) image. (Or you'll rewrite same image all the time...)
    File fi = new File("images\\inverted_" + image.getName() 
    ...
    ...