...
@Entity
public class Algo{
    ...
    // I want to skip this when GeUser entity is loading from db. Should be e.g. matches == null
    @ManyToMany(fetch = FetchType.LAZY )
    protected List<DbMatch> matches = new ArrayList<DbMatch>(); 
    ...