parent = new Parent();
parent.setName("NewParent");
Session session = util.getSession();
Transaction trans = session.beginTransaction();
LockRequest r = session.buildLockRequest(LockOptions.NONE);
r.lock(detachedChild);
parent.setChild(detachedChild);
session.save(parent);
trans.commit();
session.flush();
session.close();