String CREATE_TABLE_RECIPES = "CREATE TABLE IF NOT EXISTS " + TABLE_RECIPES + " (" +
    COLUMN_ID_2 + " INTEGER PRIMARY KEY AUTOINCREMENT, " +
    COLUMN_RECIPE_NAME + " TEXT, " +
    COLUMN_RECIPE_DESCRIPTION + " TEXT, " +
    COLUMN_RECIPE_INGREDIENTS + " TEXT, " +
    COLUMN_RECIPE_METHOD + " TEXT, " +
    COLUMN_RECIPE_NOTES + " TEXT, " +
    COLUMN_IMAGE_ID + " INTEGER " +
    COLUMN_PARENT_BOOK + " TEXT" +
    ");";