public abstract class BaseActivity extends Activity {

..................
..................
    @Override
    public void onStop() {
        super.onStop();
        // Do your stuff
    }
....................
...................
}