$(document).ready(function(){
$('#input').on('keyup',function(){
var textInput = $(this).val().trim().toLowerCase();
  if(textInput=="a"){
    $('#a').trigger('click');
    }
  if(textInput=="b"){
     $('#b').trigger('click');
    }
  if(textInput=="c"){
     $('#c').trigger('click');
    }
  if(textInput=="d"){
     $('#d').trigger('click');
    }
  if(textInput=="e"){
     $('#e').trigger('click');
    }
 
})
  $('#a').on('click',function(){
  alert("a");
  });
    $('#b').on('click',function(){
  alert("b");
  })
      $('#c').on('click',function(){
  alert("c");
  })
        $('#d').on('click',function(){
  alert("d");
  })
          $('#e').on('click',function(){
  alert("e");
  })
});