double sum = Double.valueOf(sumText.getText());
                double part = sum / 12d;
                part1Sum.setText(String.format("%.2f", part));
                part2Sum.setText(String.format("%.2f", part));
                part3Sum.setText(String.format("%.2f", part));
                part4Sum.setText(String.format("%.2f", part));
                part5Sum.setText(String.format("%.2f", part));
                part6Sum.setText(String.format("%.2f", part));
                part7Sum.setText(String.format("%.2f", part));
                part8Sum.setText(String.format("%.2f", part));
                part9Sum.setText(String.format("%.2f", part));
                part10Sum.setText(String.format("%.2f", part));
                part11Sum.setText(String.format("%.2f", part));
                part12Sum.setText(String.format("%.2f", part));