<configuration>
    <sourceRoot>${project.build.directory}/generated-code/mywebservice</sourceRoot>
    <wsdlOptions>
        <wsdlOption>
            <wsdl>${basedir}/src/main/resources/wsdl/serviceOne.wsdl</wsdl>
            <extraargs>
                <extraarg>-p</extraarg>
                <extraarg>first.packagename</extraarg>
            </extraargs>
            </wsdlOption>
        <wsdlOption>
            <wsdl>${basedir}/src/main/resources/wsdl/serviceTwo.wsdl</wsdl>
                <extraargs>
                <extraarg>-p</extraarg>
                <extraarg>another.packagename</extraarg>
            </extraargs>
        </wsdlOption>
    </wsdlOptions>
</configuration>