Classifier myClassifier = ...
CostMatrix myCostMatrix = ...
Instances myData = ...

MetaCost metaCost = new MetaCost();
metaCost.setClassifier(myClassifier);
metaCost.setCostMatrix(myCostMatrix);
metaCost.buildClassifier(myData);