public class YourResponse {
    private Detail main; // This will match "main": {}

    public static final class Detail {
       private String totalResults; // This will match "totalResults": ...
       private String libelleCategory;
       private String libelleSubCategory;
       ... bla bla....
       ... your getter/setter method....
    }
    ... your getter/setter method....
}