package com.mycompany.types;

import java.io.StringReader;
import java.io.StringWriter;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.bind.Unmarshaller;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Utility class to make it convenient to marshal and unmarshal the classes
 * generated by JAXB.
 */
@XmlTransient
public final class Utility {

  //
  // Static initialization
  //

  static {
    try {
      JAXB_CONTEXT = JAXBContext.newInstance(TestClass.class);
// The following fails with a javax.xml.bind.JAXBException.
// class mycompany.types.TestClass nor any of its super class is known
// to this context.
//      JAXB_CONTEXT =
//        JAXBContext.newInstance("com.mycompany.types",
//                                Utility.class.getClassLoader());
    }
    catch (Exception e) {
      throw new ExceptionInInitializerError(e);
    }
  }

  //
  // Constructors
  //

  //
  // Hidden constructor that prevents an object from being created.
  //
  private Utility() {
    // Do nothing.
  }

  //
  // Additional methods
  //

  /**
   * Unmarshals an XML string to a TestClass object.
   *
   * @param xml the XML string to parse
   * @return the resulting TestClass
   * @throws JAXBException if there are XML errors
   */
  public static TestClass parseTestClass(String xml) throws JAXBException {
    Unmarshaller unmarshaller = JAXB_CONTEXT.createUnmarshaller();
    return (TestClass)unmarshaller.unmarshal(new StringReader(xml));
  }

  /**
   * Marshals a TestClass object to an XML string.
   *
   * @param testClass
   * @return the resulting XML string
   * @throws JAXBException if there are XML errors
   */
  public static String printTestClass(TestClass testClass) throws JAXBException {
    Marshaller marshaller = JAXB_CONTEXT.createMarshaller();
    marshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, true);
    StringWriter writer = new StringWriter();
    marshaller.marshal(testClass, writer);
    return writer.toString();
  }

  //
  // Attributes
  //

  private static final JAXBContext JAXB_CONTEXT;

}