@Entity
public class SpecificState extends StateBase {

    //Override hook
    @Override
    public void makeTransition(Session session, State newState, StateEntity entity) {
        MyEntity myEntity = (MyEntity ) entity;
        String commentText = "some comment";
        String author = "[autogenerated]";
        addProfileComment(session, myEntity, commentText, author);
    }
}