private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
..................................
//Set selected path in text field.
JTextField_path.setText(filename);
..................................
}