class Jarvis {
    ....
    private MainActivity m;
    ....
    public Jarvis(MainActivity m) {
         this.m = m;
    }
    ....
    public void onResults(Bundle results) {
       ....
       m.next();
    }