pStmt = conn.prepareStatement("call InsertContactInfo(?,?,?,?,?,?,?,?,?)");
        pStmt.setString(1, "Mr");
        pStmt.setString(2, "Customer");
        pStmt.setString(3, "Gangadhar");
        pStmt.setString(4, "" );
        pStmt.setString(5, "T" );
        pStmt.setDate(6, null);
        pStmt.setDate(7, null);
        pStmt.setString(8, "M");
        pStmt.setString(9, "XXXXX");
        pStmt.executeUpdate();