db.scrips.aggregate([
    {
        $group:{
            "_id":"$scrip"
        }
    },
    {
        $group:{
            "_id":null,
            "scrips":{
                $push:"$_id"
            }
        }
    },
    {
        $project:{
            "_id":0
        }
    }
])