@DynamoDBTable(tableName = "Table")
public class Table {
    private String id;

    public Table() {}

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId()
    {
        return id;
    }

}