final ArrayList<CSDept> cS= new ArrayList();

// ...

public void actionPerformed(ActionEvent e) {
    // ...
    firstStudent.setStudentName(cS.get(0).getStudentName()); // ArrayList cS is empty here
    // ...