public static class MyKey {
    private int    i;
    private byte[] b;

    private MyKey(int i, byte[] b) {
        this.i = i;
        this.b = b;
    }

    public static MyKey of(int i, byte ... b) {
        return new MyKey(i, b);
    }

    @Override
    public int hashCode() {  // Autogenerated from eclipse
        final int prime = 31;
        int result = 1;
        result = prime * result + Arrays.hashCode(b);
        result = prime * result + i;
        return result;
    }

    @Override
    public boolean equals(Object obj) {  // Autogenerated from eclipse
        if(this == obj)
            return true;
        if(obj == null)
            return false;
        if(getClass() != obj.getClass())
            return false;
        MyKey other = (MyKey) obj;
        if(!Arrays.equals(b, other.b))
            return false;
        if(i != other.i)
            return false;
        return true;
    }
}

public static void main(String[] args) {
    HashMap<MyKey, Double> valueMap = new HashMap<>();
    valueMap.put(MyKey.of(1, (byte)2, (byte)4, (byte)7), 0.1);
    valueMap.put(MyKey.of(1, new byte[] { 3, 8, 14 }), 0.1);
}