{
   "results":[
      {
         "user":{
            "gender":"female",
            "name":{
               "title":"mrs",
               "first":"riley",
               "last":"barnes"
            },
     (...)