// If there is something to the left...
if (p.left != null)
    if (isLeaf(p.left))
        p.left = null;             // delete it if it's a leaf...
    else
        deleteLeaves(p.left);      // else recurse.

// If there's something to the right...
if (p.right != null)
    if (isLeaf(p.right))
        p.right = null;            // delete it if it's a leaf...
    else
        deleteLeaves(p.right);     // else recurse.