LayoutInflater layoutInflater = GenApplicationId.this.getLayoutInflater();
             View view = layoutInflater.inflate(R.layout.custom_toast, null);
             TextView tvMessage = (TextView) view.findViewById(R.id.textView1);
             tvMessage.setHeight(100);
             tvMessage.setText(message);
             Toast toast = new Toast(getApplicationContext());
             toast.setDuration(Toast.LENGTH_LONG);
             toast.setGravity(Gravity.TOP, -0, 230);
             toast.setView(view);
             toast.show();