ij> create table "APP".REGISTRATION
> (
>   id INTEGER generated by default as identity (start with 1, increment by 1) not null primary key,
>   firstname VARCHAR(50),
>   lastname VARCHAR(50),
>   username VARCHAR(50),
>   password VARCHAR(50),
>   email VARCHAR(50)
> );
0 rows inserted/updated/deleted
ij> insert into "APP".registration (firstname, lastname, username, password, email) values ('susheel', 'singh', 'susheel61', 'password', 'test@gmail.com');
1 row inserted/updated/deleted
ij> select * from REGISTRATION where USERNAME='susheel61';
ID         |FIRSTNAME                                         |LASTNAME                                          |USERNAME               |PASSWORD                                          |EMAIL
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
1          |susheel                                           |singh                                             |susheel61              |password                                          |test@gmail.com

1 row selected
ij>