JFrame.setDefaultLookAndFeelDecorated(true);
            JFrame f = new JFrame();
            f.setResizable(false);
            JPanel p = new JPanel(new GridBagLayout());
            JButton btn = new JButton("Exit");
            p.add(btn,new GridBagConstraints());
            f.getContentPane().add(p);
            f.setSize(400,300);
            f.setLocationRelativeTo(null);
            f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            f.setVisible(true);