import java.util.Arrays;

public class StackOverflow extends javax.swing.JFrame {

    String[] list;

    /**
     * Creates new form StackOverflow
     */
    public StackOverflow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        inputTxt = new javax.swing.JTextField();
        scrollPane = new javax.swing.JScrollPane();
        consoleTxt = new javax.swing.JTextArea();
        stdvBtn = new javax.swing.JButton();
        modeBtn = new javax.swing.JButton();
        medianBtn = new javax.swing.JButton();
        meanBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inputTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputTxtKeyReleased(evt);
            }
        });

        consoleTxt.setColumns(20);
        consoleTxt.setRows(5);
        scrollPane.setViewportView(consoleTxt);

        stdvBtn.setText("STDV");
        stdvBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdvBtnActionPerformed(evt);
            }
        });

        modeBtn.setText("Mode");
        modeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeBtnActionPerformed(evt);
            }
        });

        medianBtn.setText("Median");
        medianBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medianBtnActionPerformed(evt);
            }
        });

        meanBtn.setText("Mean");
        meanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meanBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputTxt)
                    .addComponent(scrollPane)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGap(0, 370, Short.MAX_VALUE)
                        .addComponent(meanBtn)
                        .addGap(18, 18, 18)
                        .addComponent(medianBtn)
                        .addGap(18, 18, 18)
                        .addComponent(modeBtn)
                        .addGap(18, 18, 18)
                        .addComponent(stdvBtn)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stdvBtn)
                    .addComponent(modeBtn)
                    .addComponent(medianBtn)
                    .addComponent(meanBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(730, 381));
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void inputTxtKeyReleased(java.awt.event.KeyEvent evt) {                                     
        list = inputTxt.getText().split(" ");
    }                                    

    private void meanBtnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        int sum = 0;

        for (String n : list) {
            sum += Integer.parseInt(n);
        }
        consoleTxt.append("The mean of the data set is  " + ((double) sum / list.length) + "\n");
    }                                       

    private void medianBtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        Arrays.sort(list);

        if (list.length % 2 == 0) {
            consoleTxt.append("The median of the data set is: " + Double.parseDouble(list[list.length / 2]) + Double.parseDouble(list[list.length / 2 - 1]) / 2 + "\n");
        } else {
            consoleTxt.append("The median of the data set is: " + list[list.length / 2] + "\n");
        }
    }                                         

    private void modeBtnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        int maxNumber = -1;
        int maxAppearances = -1;

        for (int i = 0; i < list.length; i++) {
            int count = 0;

            for (int j = 0; j < list.length; j++) {
                if (list[i].equals(list[j])) {
                    count++;
                }
            }
            if (count > maxAppearances) {
                maxNumber = Integer.parseInt(list[i]);
                maxAppearances = count;
            }
            count = 0;
        }

        consoleTxt.append("The mode of the data set: " + maxNumber + "\n");
    }                                       

    private void stdvBtnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        double STDVsum = 0.0, standardDeviation = 0.0;
        int length = list.length;

        for (String num : list) {
            STDVsum += Double.parseDouble(num);
        }

        double mean = STDVsum / length;

        for (String num : list) {
            int num_to_Integer = Integer.parseInt(num);
            standardDeviation += Math.pow(num_to_Integer - mean, 2);
        }

        consoleTxt.append("STDV " + Math.sqrt(standardDeviation / length) + "\n");
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StackOverflow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StackOverflow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StackOverflow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StackOverflow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StackOverflow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextArea consoleTxt;
    private javax.swing.JTextField inputTxt;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton meanBtn;
    private javax.swing.JButton medianBtn;
    private javax.swing.JButton modeBtn;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JButton stdvBtn;
    // End of variables declaration                   
}