new BufferedReader(new InputStreamReader(new URL("http://wiki.puzzlers.org/pub/wordlists/unixdict.txt").openStream(), StandardCharsets.UTF_8))
        .lines()
        .collect(Collectors.groupingBy(s -> Stream.of(s.split("")).sorted().collect(Collectors.joining()), Collectors.toList()))
        .entrySet().stream()
        .collect(Collectors.groupingBy(e -> e.getValue().size(), TreeMap::new, Collectors.toList()))
        .lastEntry().getValue()
        .stream().map(Map.Entry::getValue)
        .sorted(Comparator.comparing(s -> s.get(0)))
        .map(n -> n.stream().sorted().collect(Collectors.joining(" ")))
        .forEach(System.out::println);