String TABLE_CREATE = "CREATE TABLE " + TABLE_NAME + " ("
        + RENDEZ_VOUS_ID  + " INTEGER PRIMARY KEY AUTOINCREMENT, "
        + DATE + " DATE, "
        + TIME + " TIME, "
        + STATUS + " INTEGER, "
        + COMMENT + " TEXT, "
        + CONTACT_ID + " INTEGER, "
        + OTHER_ID +  " INTEGER, "
        + FOREIGN KEY("+CONTACT_ID+") REFERENCES "+DatabaseManagerContact.TABLE_NAME+"("+CONTACT_ID+"), "
        + FOREIGN KEY("+OTHER_ID+") REFERENCES "+DatabaseManagerContact.ANOTHER_TABLE_NAME+"("+ANOTHER_ID+"));";