TAbleA.queryBuilder()
                    .where()
                    .eq("col1", Wait)
                    .eq("col2", Fail)
                    .or(2)
                    .isNull("col3")
                    .le("col4", fromThisTime)
                    .or(2)
                    .and(2)
                    .prepare();