BorderPaneBuilder.create()
    .top(ToolBarBuilder.create()
        .items(ButtonBuilder.create()
            .text("Add New Row")
            .onAction(e -> backendItemList.add(new MyItem("<NEW>", "<NEW>")))
            .build())
        .build())
    .center(
        TableViewBuilder.<CustomColumnNameMapping> create()
            .items(backendItemList)
            .editable(true)
            .columns(
                TableColumnBuilder.<CustomColumnNameMapping, String> create()
                    .text("Column1 for property1")
                    .cellValueFactory(new WritablePropertyValueFactory<>("property1"))
                    .cellFactory(TextFieldTableCell.forTableColumn())
                    .editable(true)
                    .build(),
                TableColumnBuilder.<CustomColumnNameMapping, String> create()
                    .text("Column2 for property2")
                    .cellValueFactory(new WritablePropertyValueFactory<>("property2"))
                    .cellFactory(TextFieldTableCell.forTableColumn())
                    .editable(true)
                    .build())
            .build())
    .build();