class Product {
  List<Product> children ...
  double basePrice ...

  Product(double basePrice) { ...

  Product(List<Product> children) { ...

  double getPrice() { 
    if (children.isEmpty()) return basePrice;
    else return SUM over getPrice() called on each child