/**
Builder class for javafx.scene.shape.Rectangle
@see javafx.scene.shape.Rectangle
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public class RectangleBuilder<B extends javafx.scene.shape.RectangleBuilder<B>> extends javafx.scene.shape.ShapeBuilder<B> implements javafx.util.Builder<javafx.scene.shape.Rectangle> {