...
@Override
public void paintComponent(Graphics g){
    int x, y;
    int prevX, prevY;
    int maxX, maxY;
    ...
    //retrieve values from your model for the declared variables
    ...
    //calculate the coords of your line on the canvas
    int xPos = ((x / maxX) * X_AXIS_LENGTH) + X_AXIS_OFFSET;
    ...
    //do the same for y, prevX, prevY and then you can use g.drawLine
}
...