ToImageOptionsSpec spec = new ToImageOptionsSpec(); 
spec.setImageConvertFormat(ImageConvertFormat.TIFF); 
spec.setGrayScaleCompression(GrayScaleCompression.None); 
spec.setMultiPageTiff(true);
spec.setColorSpace(ColorSpace.Monochrome); 
spec.setResolution("300");
spec.setMonochrome(MonochromeCompression.CCITTG4); 
spec.setGrayScalePolicy(GrayScalePolicy.Off); 
//spec.setImageSizeHeight(PageSize.Letter.getHeight());
//spec.setImageSizeWidth(PageSize.Letter.getWidth());