........
   ........
   public static void zodiacSign(int day, int month, Context c)
   {
    if (...) {
        ....
        ...

        Intent intent=new Intent(c, AriesActivity.class);
        c.startActivity(intent);
       }
    }