JPanel panel = ...
...
...
File yourFileHere = ...
...
...
BufferedImage img = new BufferedImage(panel.getWidth(), panel.getHeight(), BufferedImage.TYPE_INT_ARGB);
Graphics g = img.getGraphics();
panel.paint(g);
g.dispose();

try{
    ImageIO.write(img, "png", yourFileHere);
}catch(IOException e){
    e.printStackTrace();
}