CREATE OR REPLACE VIEW FULL_NAME_LIST_VIEW AS SELECT 
    N.NAME_ID AS ID, 
    N.DISPLAY DISPLAY,
    'BOSS' TYPE
FROM NAME N
UNION
SELECT 
    NI.NAME_INDEX_ID AS ID,
    (FIRST.DISPLAY || ' - ' || LAST.DISPLAY) AS DISPLAY,
    NI.TYPE_ID TYPE
FROM NAME_INDEX NI,
     NAMEHOLDER FIRST,
     NAMEHOLDER LAST
WHERE NI.FIRST_ID = FIRST.NAME_ID
AND NI.LAST_ID = LAST.LAST_ID;