static final String CREATE_NEW_LEAD_TABLE = "CREATE TABLE "+ TABLE_NEW_LEAD + "("
                                            + KEY_NEW_LEAD_ID + " INTEGER PRIMARY KEY AUTOINCREMENT, " 
                                            + KEY_ORGANIZATION_NAME + " TEXT,"
                                            + KEY_NEW_LEAD_NAME + " TEXT, "
                                            + KEY_NEW_LEAD_EMAIL+ " TEXT, "
                                            + KEY_NEW_LEAD_MOBILE + " TEXT, "
                                            + KEY_NEW_LEAD_Product + " TEXT, "
                                            + KEY_NEW_LEAD_BUDGET + " TEXT, "
                                            + KEY_NEW_LEAD_PRIORITY + " TEXT, "
                                            + KEY_NEW_LEAD_STATUS + " TEXT, "
                                            + KEY_NEW_LEAD_NOTES + " TEXT, "
                                            + KEY_NEW_LEAD_REMINDER_DATE + " TEXT, "
                                            + KEY_NEW_LEAD_REMINDER_TIME + " TEXT, "
                                            + KEY_NEW_LEAD_ADDtoCONTACTS + " TEXT, "
                                            + KEY_NEW_LEAD_CurrentDate + " TEXT "+");";