Outer outer = ...
  Inner inner1 = outer.new Inner(...);
  Inner inner2 = outer.new Inner(...);
  ...
  ObjectOutputStream oos = ...
  oos.writeObject(inner1);
  oos.writeObject(inner2);
  oos.close();
  ...
  ObjectInputStream ois = ...
  Inner deserialized_inner1 = (Inner) ois.readObject();
  Inner deserialized_inner2 = (Inner) ois.readObject();