...
private static final String FAKE_CSV="John\t123-456\nJane\t456-123\n";
private static final StringReader FAKE_CSV_READER = new StringReader(FAKE_CSV);
...
{
  ...
   getPhone(FAKE_CSV_READER);
  ...
}
...