with cte as (. . .)
SELECT . . .
FROM (SELECT t.*, ROW_NUMBER() OVER (PARTITION BY t.PRTCPNT_DCN ORDER BY t.PRTCPNT_DCN) as RN
      FROM PRTCPNT_ELIG_SPAN_T t 
     ) t INNER JOIN
     CTE
     ON CTE.PRTCPNT_DCN = t.PRTCPNT_DCN AND
        CTE.PRTCPNT_ELIG_END_DATE = t.PRTCPNT_ELIG_END_DATE AND
        CTE.RN1 = t.RN;