public class PriorityQueue<E> implements Iterator<QueueItem<E>> {
    ...
    private Map<Integer, List<QueueItem<E>>> pq;
    ...
}

public class QueueItem<E> implements Comparable<QueueItem<E>> {
    ...
    private E value;
    ...
}