<Resource name="jdbc/xxx"
    auth="Container"
    type="javax.sql.DataSource"
    factory="com.yyy.tomcat.jndi.EncryptedDataSourceFactory"
    username="xyz"
    password="abc"
    driverClassName="com.mysql.jdbc.Driver"
    url="jdbc:mysql://x.x.x.x:3306/abc?enableQueryTimeouts=true&amp;autoReconnect=true&amp;autoReconnectForPools=true"
    initialSize="0"
    maxTotal="100"
    maxActive="100"
    minIdle="0"
    maxWait="1000"
    testOnBorrow="true"
    testWhileIdle="true"
    validationQuery="SELECT 1"
    validationInterval="30000"
    validationQueryTimeout="1"
    timeBetweenEvictionRunsMillis="30000"
    minEvictableIdleTimeMillis="30000"
    removeAbandonedTimeout="10"
    removeAbandoned="true"
    logAbandoned="true"
    logValidationErrors="true"
    connectionProperties="[enableQueryTimeouts=true]"
    jdbcInterceptors="ConnectionState;QueryTimeoutInterceptor(queryTimeout=1);SlowQueryReport;ResetAbandonedTimer">