// Instance one...
start_button.addActionListener(new MainPanel());
//...
// Instance two...
//calls the content_Walls class and sends the number of ovals to be generated
content.add(new MainPanel());