// Break the input apart at the spaces...
String[] parts = input.split(" "); 
// We only care if there are two parts...
if (parts.length == 2) {
    // Process the parts...
} else if (parts.length == 0 || !"quite".equalsIgnoreCase(parts[0])) {
    System.out.println("Your selection is invalid");
}