String sql = "INSERT INTO PUNCHOUT_USER_LOGIN(REQ_TIME) VALUES(?)";
// ...

try {
    // ...
    preparedStatement = connection.prepareStatement(sql);
    preparedStatement.setTimestamp(1, timestamp);
    // ...
} finally {
    // ...
}