JNIEXPORT jintArray JNICALL Java_IntArrayViaJNI_intArrayMethod(
        JNIEnv *env, jclass cls,
        /* generated by JAVAH: float[] t, int nb_of_subscribers, int tags */)
    {
      jintArray result = (*env)->NewIntArray(env, size);
      if (result == NULL) {
        return NULL; /* out of memory error thrown */
      }
      int i, size = MY_ARRAY_SIZE;

      // Populate a temp array with primitives.
      jint fill[256];
      for (i = 0; i < size; i++) {
        fill[i] = MY_ARRAY_VALUE;
      }

      // Let the JVM copy it to the Java structure.
      (*env)->SetIntArrayRegion(env, result, 0, size, fill);
      return result;
    }