SELECT
    SURVEY.* , 
    COUNT(RESPONSE.OFFLINE_ID) AS responseCount
FROM
    SURVEY
LEFT OUTER JOIN
    RESPONSE
ON
    SURVEY.OFFLINE_ID = RESPONSE.OFFLINE_SURVEY_ID 
GROUP BY
    SURVEY.OFFLINE_ID;