public void Insert(Map<String, Object> parameters, String TableName)
{       
   JdbcInsert = new SimpleJdbcInsert(this.jdbcTemplate).withTableName(TableName);
   //This column won't be included on the insert statement (it will be autogenerated by SQL Server)
   JdbcInsert.setGeneratedKeyName("id");
   JdbcInsert.execute(parameters);
}