public void onSaveInstanceState(Bundle onState){
    onState.getInt.....

public void onSaveInstanceState(Bunble savedInstanceState){
    savedInstanceState.getInt...

public void onSaveInstanceState(Bunble whatEverYouLike){
    whatEverYouLike.getInt...