<%
    // (Be sure to URL-encode the value if necessary, not shown here)
    String formAction = response.encodeURL("action.jsp?hiddenData=" + hiddenValue);
%>
...
<form action="<%=formAction%>">
...
</form>
...
<form action="<%=formAction%>">
...
</form>
...