public final class ObjectTypeAdapter extends TypeAdapter<Object> {
...

    @Override public Object read(JsonReader in) throws IOException {
...
        case NUMBER:
            return in.nextDouble();
...