/**
 * Creates Workbook instance based on .xls template from a given InputStream and a number of beans
 *
 * @param is         xls InputStream with required
 * @param beanParams Beans in a map under keys used in .xls template to access to the beans
 * @return new {@link org.apache.poi.ss.usermodel.Workbook} generated by inserting beans into corresponding excel template
 * @throws net.sf.jxls.exception.ParsePropertyException if there were any problems in evaluating specified property value from a bean
 */
public org.apache.poi.ss.usermodel.Workbook transformXLS(InputStream is, Map beanParams) throws ParsePropertyException, InvalidFormatException {
    org.apache.poi.ss.usermodel.Workbook hssfWorkbook = null;
    try {
        hssfWorkbook = WorkbookFactory.create(is);
        transformWorkbook(hssfWorkbook, beanParams);
    } catch (IOException e) {
        e.printStackTrace();
    }
    return hssfWorkbook;
}