Containercp = getContentPane();
//cp.setLayout(new GridLayout(4,5));
//cp.add(canvas, f1);
//cp.add(btnPanel,f1);
//cp.add(CentrePanel,f1);
//cp.add(DownPanel,f1);
add(canvas, BorderLayout.CENTER);
Box pageEnd = Box.createVerticalBox();
btnUp.setAlignmentX(0.5f);
pageEnd.add(btnUp);
pageEnd.add(CentrePanel);
btnDn.setAlignmentX(0.5f);
pageEnd.add(btnDn);
add(pageEnd, BorderLayout.PAGE_END);