public void someMethod(int dynamicInt){

    ArrayList<SomeClass> someClassArray = new ArrayList<SomeClass>();
       //SomeClass[] someClassArray = new Some Class[0];//initialization generated by ide
       for (int i=0; i<=dynamicInt; i++){
          SomeClass c = new SomeClass();
          c.setSomeInfo(getSomeInfo());
          someClassArray.add(c);
       }
    }