PdfReader pdfReader = new PdfReader(byteArrayOutputStream.toByteArray());
PdfStamper stamper = new PdfStamper(pdfReader, byteArrayOutputStream);  
PdfFormField field = PdfFormField.createSignature(stamper.getWriter()); 
field.setFieldName("Digital Signature");
field.setWidget(new Rectangle(line.x, line.y, line.x + line.width, line.y - line.height), PdfAnnotation.HIGHLIGHT_OUTLINE);
field.setFlags(PdfAnnotation.FLAGS_PRINT);  
field.setColor(BaseColor.WHITE);  
field.setMKBorderColor(BaseColor.BLACK);  
stamper.addAnnotation(field, pageNumber);  
stamper.close();