<PlaceWareConfCenter>
   <CreateMeetingReply>
      <MeetingReply>
         <OptionList>
            <StringOption value="Jeff Hay has invited you to attend an online meeting using&#xD;&#xA;Microsoft Office Live Meeting.&#xD;&#xA;&#xD;&#xA;https://www.livemeeting.com/cc/contoso/join?id=name10&role=attend&pw=auPa%24%24w0rd&#xD;&#xA;&#xD;&#xA;&#xD;&#xA;&#xD;&#xA;AUDIO INFORMATION&#xD;&#xA;Audio has not been set up for this meeting.&#xD;&#xA;&#xD;&#xA;&#xD;&#xA;FIRST-TIME USERS&#xD;&#xA;To save time before the meeting, check your system to make sure it is&#xD;&#xA;ready to use Microsoft Office Live Meeting. &#xD;&#xA; http://go.microsoft.com/fwlink/?linkid=52354&#xD;&#xA;&#xD;&#xA;TROUBLESHOOTING &#xD;&#xA;Unable to join the meeting? Follow these steps:&#xD;&#xA;  1. Copy this address and paste it into your Web browser:&#xD;&#xA;     https://www.livemeeting.com/cc/contoso/join&#xD;&#xA;  2. Copy and paste the required information:&#xD;&#xA;        Meeting ID: name10&#xD;&#xA;        Entry Code: auPa$$w0rd&#xD;&#xA;        Location: https://www.livemeeting.com/cc/contoso/join&#xD;&#xA;If you still cannot enter the meeting, contact support:&#xD;&#xA;http://r.office.microsoft.com/r/rlidLiveMeeting?p1=7&p2=en_US&p3=LMInfo&p4=support" name="audienceInviteText">
            </StringOption>
            <StringOption value="Jeff Hay has invited you to present an online meeting using&#xD;&#xA;Microsoft Office Live Meeting.&#xD;&#xA;&#xD;&#xA; https://www.livemeeting.com/cc/contoso/xmlapi6/join?id=name10&role=present&pw=prPa%24%24w0rd&#xD;&#xA;&#xD;&#xA;&#xD;&#xA;&#xD;&#xA;AUDIO INFORMATION&#xD;&#xA;Audio has not been set up for this meeting.&#xD;&#xA;&#xD;&#xA;&#xD;&#xA;FIRST-TIME USERS&#xD;&#xA;To save time before the meeting, check your system to make sure it is&#xD;&#xA;ready to use Microsoft Office Live Meeting. &#xD;&#xA; http://go.microsoft.com/fwlink/?linkid=52354&#xD;&#xA;&#xD;&#xA;TROUBLESHOOTING &#xD;&#xA;Unable to join the meeting? Follow these steps:&#xD;&#xA;  1. Copy this address and paste it into your Web browser:&#xD;&#xA;     https://www.livemeeting.com/cc/contoso/join&#xD;&#xA;  2. Copy and paste the required information:&#xD;&#xA;        Meeting ID: name10&#xD;&#xA;        Entry Code: prPa$$w0rd&#xD;&#xA;        Location: https://www.livemeeting.com/cc/contoso/join&#xD;&#xA;If you still cannot enter the meeting, contact support:&#xD;&#xA;http://r.office.microsoft.com/r/rlidLiveMeeting?p1=7&p2=en_US&p3=LMInfo&p4=support" name="presenterInviteText">
            </StringOption>
         </OptionList>
      </MeetingReply>
   </CreateMeetingReply>
</PlaceWareConfCenter>