DELIMITER $$
CREATE FUNCTION MAC_ADDR
  (
   M BIGINT
  ) RETURNS VARCHAR(17)
  LANGUAGE SQL
  DETERMINISTIC
  READS SQL DATA
  BEGIN
    DECLARE TMP BIGINT;
    DECLARE RESULT VARCHAR(17) DEFAULT '';
    DECLARE B INTEGER;
    DECLARE I INTEGER DEFAULT 0;
    IF (M IS NOT NULL AND M > 0) THEN
      SET TMP = M;
      LOOP
        IF I > 0 THEN
          SET RESULT = ':' || RESULT;
        END IF;
        SET RESULT = SUBSTR(HEX(BITAND(TMP, 15)), 2, 1) || RESULT;
        SET RESULT = SUBSTR(HEX(BITAND((TMP / 16), 15)), 2, 1) || RESULT;
        SET TMP = TMP / 256;
        SET I = I + 1;
        IF (I > 5) THEN
          RETURN UPPER(RESULT);
        END IF;
      END LOOP;
    END IF;
    RETURN '00:00:00:00:00:00';
  END$$
DELIMITER ;