String s = Dashboard.mail_seller.getSelectedItem().toString();
            String selected[] = s.split(" -- ");
            String seller_id = selected[0].trim();
            String filename = sale_date + "_" + selected[1].replaceAll(" ", "_").trim() + ".pdf";
            String reportName = reportPath + "AuctionSale/AuctionSellerMail/AuctionSeller.jasper";
            Map<String, Object> params = new HashMap<String, Object>();
            params.put("sale_date", sale_date);
            params.put("seller_id", seller_id);
            JasperPrint jasperPrint = JasperFillManager.fillReport(reportName, params, DB.getConn());
            OutputStream output = new FileOutputStream(new File("D:/Netbeans Projects/JDSons/mail_reports/"+filename+"")); 
            JasperExportManager.exportReportToPdfStream(jasperPrint, output); 
            output.flush();
            output.close();