@Repository
public class ClientRepository {

    //The code below is optional, but will work if you want to use jdbctemplate tied to the DataSource created above. By default all Hibernate Sessions will take the DataSource generated by Spring
    @Bean(name = "myProjectJdbcTemplate")
    public JdbcTemplate jdbcTemplate(@Qualifier("myProjectDataSource") DataSource dataSource){
        return new JdbcTemplate(dataSource);
    }
}