do {
    /*
        if (Operation == 1) {
                 ...
                 ...
                 ...
        else {
                 ...
        }
    */
    System.out.print("Would you like to do another calculation? [Y/n] ");
} while (input.nextLine().toUpperCase().charAt(0) == 'Y');