String str = "{\"status\": \"OK\","+
        "\"usage\": \"By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html\","+
        "\"url\": \"http://www.theage.com.au/world/aussie-trying-to-make-a-difference-gunned-down-20110510-1egnv.html\","+
        "\"language\": \"english\","+
        "\"keywords\": ["+
            "{"+
                "\"text\": \"Mr McNichols\","+
                "\"relevance\": \"0.99441\""+
            "},"+
            "{"+
                "\"text\": \"Ms Benton\","+
                "\"relevance\": \"0.392337\""+
            "},"+
            "{"+
                "\"text\": \"Detroit\","+
                "\"relevance\": \"0.363931\""+
            "},"+
            "{"+
                "\"text\": \"Crocodile Hunter\","+
                "\"relevance\": \"0.350197\""+
            "}"+
            "]"+
        "}";

        Gson gson = new Gson();
        MyJSON mj = gson.fromJson(str, MyJSON.class);
        System.out.println(mj.language);
        for(Keyword k: mj.keywords)
            System.out.println(k.text+":"+k.relevance);