ResultSetHandler<List<Map<String, Object>>> resultHandler = genericResultHandler();

    List<Map<String, Object>> result = null;

    // Execute the SQL statement and return the results in a List of
    // T objects generated by the BeanListHandler.
    try
    {
        result = run.query(sqlQuery, resultHandler, varargs);
    }
    catch (SQLException e)
    {
        e.printStackTrace();
    }

    result.stream().forEach(System.out::println);