ConsoleAppender caInfo = new ConsoleAppender();
    caInfo.setName("infoConsole");
    caInfo.setThreshold(Level.DEBUG);
    layout.setConversionPattern("%-5p %d [%t] %c %x - %m%n");
    caInfo.setLayout(layout);
    LevelRangeFilter lrf = new LevelRangeFilter();
    lrf.setLevelMax(Level.DEBUG);
    lrf.setLevelMin(Level.DEBUG);
    caInfo.addFilter(lrf);
    caInfo.activateOptions();
    logger.addAppender(caInfo);