OptimizationProblem op = new OptimizationProblem();
...
op.addDecisionVariable("m", false, new int[]{1, 1});
...
op.addConstraint("m<=100");//<- the constraints
...
op.setInitialSolution("m", 50);//optional
...
op.setObjectiveFunction("minimize", str);//where str is the string representing the function to minimize
...
System.loadLibrary("Ipopt38");
op.solve("ipopt");
...
if (!op.solutionIsOptimal()) {
        return null;
}

features[0] = op.getPrimalSolution("m").toValue();
...
features[3] = op.getOptimalCost();