while(!(guessedSpaces.replaceAll("\\d","").length()==3 && guessedSpaces.split(" ").length-1==3)){
    .....
    .....
    System.out.println("Enter word with white-spaces:");
    guessedSpaces = keyboard.nextLine();
}