public void validateMulti(FacesContext context, UIComponent component, Object value){
  ...
  UIInput minInput = (UIInput) component.findComponent("minYear");
  ...
  context.addMessage("minYear", new FacesMessage(valMsg, valMsg));
  ...