setLayout(new GridBagLayout());
GridBagConstraints gbc = new GridBagConstraints();
gbc.gridx = 0;
gbc.gridy = 0;
gbc.anchor = GridBagConstraints.WEST;
add(new JLabel("Enter Length #1"), gbc);
gbc.gridy++;
add(new JLabel("Enter Length #2"), gbc);
gbc.gridy++;
add(new JLabel("Enter Length #3"), gbc);
gbc.gridy++;
add(new JLabel("Enter Length #4"), gbc);
gbc.gridy++;
add(new JLabel("Average"), gbc);

gbc.gridx++;
gbc.gridy = 0;
gbc.fill = GridBagConstraints.HORIZONTAL;
add(new JTextField(10), gbc);
gbc.gridy++;
add(new JTextField(10), gbc);
gbc.gridy++;
add(new JTextField(10), gbc);
gbc.gridy++;
add(new JTextField(10), gbc);
gbc.gridy++;
JLabel average = new JLabel(" ");
average.setBorder(BorderFactory.createLineBorder(Color.BLACK));
add(average, gbc);