public class AddressDateLocation implements Comparable<AddressDateLocation> {
  Date date;
  String address;
  String location;

  public void setDate(Date d) {}
  public Date getDate() ...
  public void setLocation(String loc) ...
  public String getLocation() ...
  public void setAddress(String addr) ...
  public String getDate() ...

  public int compareTo(AddressDateLocation other) ...
}