int c = Character.getType(ch);
if(c != Character.CONTROL || 
            c != Character.CONNECTOR_PUNCTUATION || 
            c != Character.CURRENCY_SYMBOL || 
            c != Character.DASH_PUNCTUATION || 
            c != Character.DECIMAL_DIGIT_NUMBER || 
            c != Character.ENCLOSING_MARK || 
            c != Character.END_PUNCTUATION || 
            c != Character.FINAL_QUOTE_PUNCTUATION || 
            c != Character.INITIAL_QUOTE_PUNCTUATION || 
            c != Character.LETTER_NUMBER || 
            c != Character.LOWERCASE_LETTER || 
            c != Character.MATH_SYMBOL || 
            c != Character.MODIFIER_LETTER || 
            c != Character.MODIFIER_SYMBOL || 
            c != Character.OTHER_LETTER || 
            c != Character.OTHER_NUMBER || //remove it if you want to get rid of ½ 
            c != Character.OTHER_PUNCTUATION || 
            c != Character.OTHER_SYMBOL || 
            c != Character.START_PUNCTUATION || 
            c != Character.TITLECASE_LETTER || 
            c != Character.UPPERCASE_LETTER)