Map<HQ,List<HQ>> winnersByWinner = node.getConnection().stream()
            .map(Node::getHQ)
            .filter(Objects::nonNull)
            .collect(Collectors.groupingBy(Function.identity()))
   HQ winner = winndersByWinnder.entrySet().stream()
            .map(e -> new AbstractMap.SimpleImmutableEntry<>(e.getKey(), e.getValue().size()))
            .sorted(Comparator.comparingInt(Map.Entry::getValue).reversed())
            .map(Map.Entry::getKey)
            .findFirst()
            .orElseGet(null);