CREATE OR REPLACE VIEW UIV AS
SELECT * FROM (
SELECT
(SELECT FIR_KO_KREIS FROM FIRMA
WHERE FIR_KONZERN_NR = TRCO_KONZERN_NR
AND FIR_FIRMA_NR = TRCO_FIRMA_NR) UIVNFIRMA,
UIVAAENNKZ UIVAAENKZ,
UVVOL,
UVCLS,
UVID1,
.
.
.
FROM CO_BUCH);