CREATE TABLE "REVINFO" 
   (    "REV" NUMBER(10,0) NOT NULL ENABLE, 
"REVTSTMP" NUMBER(19,0), 
PRIMARY KEY ("REV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "DBA_DATA1_TS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "DBA_DATA1_TS" ;