RegexExtractor regexExtractor = new RegexExtractor();
regexExtractor.setName("Regular Expression Extractor");
regexExtractor.setProperty("RegexExtractor.useHeaders", "false");
regexExtractor.setProperty("RegexExtractor.refname", "yourVariable");
regexExtractor.setProperty("RegexExtractor.regex", "yourRegex");
regexExtractor.setProperty("RegexExtractor.template", "yourTemplate");
regexExtractor.setProperty("RegexExtractor.match_number", "yourMatchNumber");
regexExtractor.setProperty("RegexExtractor.default", "yourDefaultValue");
regexExtractor.setProperty(TestElement.TEST_CLASS, RegexExtractor.class.getName());
regexExtractor.setProperty(TestElement.GUI_CLASS, RegexExtractorGui.class.getName());