find.fetch("trackToArtists.artist.artistToTags")
    .where()
    .eq(join, station)
    .ge(join + ".energyMin", settings.energyMin)
    .le(join + ".energyMax", settings.energyMax)
    .ge(join + ".livenessMin", settings.livenessMin)
    .le(join + ".livenessMax", settings.livenessMax)
    .ge(join + ".tempoMin", settings.tempoMin)
    .le(join + ".tempoMax", settings.tempoMax)
    .ge(join + ".acousticnessMin", settings.acousticnessMin)
    .le(join + ".acousticnessMax", settings.acousticnessMax)
    .ge(join + ".danceMin", settings.danceMin)
    .le(join + ".danceMax", settings.danceMax)
    .orderBy("trackToArtists.artist.artistToTags.score DESC")
    .setMaxRows(Util.TopN)
    .findList();