create or replace
TRIGGER BI_OPERATION_REG BEFORE INSERT 
    ON OPERATION_REG 
    REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW 
BEGIN
    IF :NEW.ID IS NULL THEN SELECT SEQ_OPERATION_REG.NEXTVAL INTO :NEW.ID FROM dual; END IF;
EXCEPTION
   WHEN OTHERS
   THEN
      RAISE_APPLICATION_ERROR (-20255, 'ERROR EN TRIGGER BI_OPERATION_REG');
END;