ServerSocket socket1;
...
void setup()
{
 ...
   ServerSocket socket1... /* here you want to use the socket above...
   but you declare a socket variable with the same signature,
   so to compiler will ignore the field above and will use your local
   variable...

   When you try to use the field he will be null because you do not affected
   your state.*/