@RunWith(AndroidJUnit4.class)
public class TestYard {

    //assign these test rule to the test
    @Rule
    public ActivityTestRule testRule = new ActivityTestRule(false,false); 


    @Test
    public void testDynamicLink() {

        //Dynamic link url
        String url = "https://....app.goo.gl/...";

        //create intent
        Intent intent = new Intent (Intent.ACTION_VIEW);
        intent.setData (Uri.parse(url));

        //launch activity with the url as intent. Should work exactly as open from the email generated by Firebase invite function.
        testRule.launchActivity(intent);
    }
}