// The catalogue literal object
var catalogue = {

sortDirection: -1, // The direction of the sort
product: [], // The product list generated by the JSP


// Sorts the products by their ID
sortById: function sortById() { 
    catalogue.product.sort(function(a, b) {
        return catalogue.sortDirection * (a.pId - b.pId);
    });
    catalogue.sortDirection *= -1;      
    catalogue.display();
},


// Sorts the products by their NAME
sortByName: function sortByName() {
    catalogue.product.sort(function(a, b) {
        var result = 0;
        var nameA = a.pName.toLowerCase(), nameB = b.pName.toLowerCase();
        if (nameA < nameB) {
            result = -1;
        } else if (nameA > nameB) {
            result = 1;
        } else {
            result = 0;
        }
        return catalogue.sortDirection*result;          
    });

    catalogue.sortDirection *= -1;  
    catalogue.display();
},


// Sorts the products by their PRICE
sortByPrice: function sortByPrice() {
    catalogue.product.sort(function(a, b) {
        return catalogue.sortDirection * (a.pPrice - b.pPrice);
    });
    catalogue.sortDirection *=  -1; 
    catalogue.display();
},


// Displays the sorted products
display: function display(){        

    var node = document.getElementById('container');
    while (node.hasChildNodes()) {
        node.removeChild(node.firstChild);
    }

    var html = "";

    for(var i = 0; i < catalogue.product.length; i++){              
        var tableRow = new catalogue.tableRow(catalogue.product[i]);  
        html += tableRow.generateHTML();    
    }

    document.getElementById('container').innerHTML = html;
},


// Contructor object for the table row
tableRow: function tableRow(product){

    this.id = product.pId;
    this.image = product.pImage;
    this.name = product.pName;
    this.price = product.pPrice;
    this.feature = product.pFeature;

    var image = "<div id='mainitemlist'><div id='mainitemlistimage'><a href='product?pid=prdID'><img src='product_images/prdIMAGE'></a></div>";
    var name = "<div id='mainitemlistname'><a href='product?pid=prdID'>prdNAME</a></div>";
    var price = "<div id='mainitemlistprice'>prdPRICE</div>";
    var features = "<div id='mainitemlistfeatures'>prdFEATURE</div></div>";


    this.generateHTML = function generateHTML(){
        html = "";      
        html += image.replace("prdIMAGE", this.image).replace("prdID", this.id);
        html += name.replace("prdNAME", this.name).replace("prdID", this.id);
        html += price.replace("prdPRICE", this.price);
        html += features.replace("prdFEATURE", this.feature);
        return html;        
    };

}

};