public void go() {
    JPanel buttonPanel= new JPanel();
    buttonPanel.setLayout(new BorderLayout());
    Font font = new Font("Times New Roman", Font.BOLD, 70);
    JFrame frame = new JFrame("GAME");
    JLabel label=new JLabel("Green");
    label.setFont(font);
    label.setHorizontalAlignment(JLabel.CENTER);
    label.setForeground(Color.blue);
    JButton button1 = new JButton("blue");
    JButton button2 = new JButton("red");
    JButton button3 = new JButton("green");
    buttonPanel.add(button1,BorderLayout.WEST);
    buttonPanel.add(button2,BorderLayout.SOUTH);
    buttonPanel.add(button3,BorderLayout.EAST);
    buttonPanel.add(label,BorderLayout.CENTER);
    button1.addActionListener(new Level2());
    button2.addActionListener(new Gameover());
    button3.addActionListener(new Gameover());
    button1.setForeground(Color.black);
    button2.setForeground(Color.black);
    button3.setForeground(Color.black);
    button1.setBackground(Color.white);
    button2.setBackground(Color.white);
    button3.setBackground(Color.white);
    frame.setSize(500, 500);
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    frame.getContentPane().add(buttonPanel);
    frame.setVisible(true);
}