// Get hash code as hexadecimal string (generated by crypto-js)
String digest = servletRequest.getParameter("digest");

// hexadecimal to string decoder
byte[] decodedHex = Hex.decodeHex(digest.toCharArray());

// Timestamp request
TimeStampRequestGenerator reqgen = new TimeStampRequestGenerator();
TimeStampRequest req = reqgen.generate(TSPAlgorithms.SHA256, decodedHex);
byte request[] = req.getEncoded();
...