ServiceGenerateFromWSImportWhichIsTheSameAsYour iService = 
   new ServiceGenerateFromWSImportWhichIsTheSameAsYour().
            getServiceGenerateFromWSImportWhichIsTheSameAsYourPort();

// now on iServie instance you can invoke method from your webservice
// but you have to use stub classes generated by wsimport

iService.myMethodWhichGetFileList(List<SoapFileStubGeneratedClass> sopaFiles);