Map<String, String> option1 = new HashMap<String, String>();
    option1.put("value", "0");
    option1.put("level", "zero");
    options.add(option1);
    Map<String, String> option2 = new HashMap<String, String>();
    option2.put("value", "1");
    option2.put("level", "one");
    options.add(option2);
    Map<String, String> option3 = new HashMap<String, String>();
    option3.put("value", "2");
    option3.put("level", "two");
    options.add(option3);