public class LabelExample {

...

/**
 * This class was generated by MyBatis Generator. This class corresponds to the database table Label
 * @mbggenerated
 */
    protected abstract static class GeneratedCriteria {

        public Criteria andLabelNameEqualTo(String value) {
            addCriterion("binary Label_Name =", value, "labelName");
            return (Criteria) this;
        }
    ...
}