create or replace PROCEDURE GETREGISTRATIONRECORDS 
(
   MY_CURSER OUT SYS_REFCURSOR,
   REGID IN NUMBER 
) AS 
BEGIN
OPEN MY_CURSER FOR
SELECT * FROM REGISTRATION
WHERE ID=REGID;
END GETREGISTRATIONRECORDS;