CREATE TABLE cuenta (
    CUENTA INTEGER AUTO_INCREMENT PRIMARY KEY,
    CLIENTE_ID INT,
    SALDOAFAVOR NUMERIC(14, 2),
    SALDOENCONTRA NUMERIC(14, 2),
    FECHACORTE DATE,
    LIMITECREDITO NUMERIC(14,2),
    FOREIGN KEY(CLIENT_ID) REFERENCES clientes(ID)
);