Schema schema = ReflectData.get().getSchema(User.class);
        DatumWriter<GenericRecord> datumWriter = new GenericDatumWriter<GenericRecord>(schema);
        DataFileWriter<GenericRecord> dataFileWriter = new DataFileWriter<GenericRecord>(datumWriter);
        ByteArrayOutputStream output = new ByteArrayOutputStream();
        dataFileWriter.create(schema, output);
        GenericRecord user = createGenericRecord(schema);
        dataFileWriter.append(user);
        dataFileWriter.close();
        byte[] bytes = output.toByteArray();
        System.out.println(new String(bytes));