(?!                assert that there is no...
   \w+             ...sequence of characters...
   (?:AB|BCC|CDD)  ...followed by AB, BCC, or CDD...
   -               ...and a dash
)
[A-Z]{2,4}-        then simply match 2 to 4 characters before a dash