Calendar calendar = Calendar.getInstance();
        int year=2015;
        int month=7;
        int date=31;
        int hourOfDay=23;
        int minute=59;
        int second=59;
        int milliSecond=999;
        calendar.set(year, month, date, hourOfDay, minute, second);
        calendar.set(calendar.MILLISECOND, milliSecond);
        System.out.println("Time from Calendar: "+calendar.getTime());
        long timeInMilliSeconds=calendar.getTimeInMillis();
        System.out.println("timeInMilliSeconds from calendar: "+timeInMilliSeconds);
        Timestamp timestamp=new Timestamp(timeInMilliSeconds);
        System.out.println(timestamp);