args = new String[12];
    args[0]="-s";
    args[1]="source_port";// something integer value "1324"
    args[2]="-h";
    args[3]="hostname";
    args[4]="-p";
    args[5]="port";
    args[6]="-l";
    args[7]="log_file";
    args[8]="-m";
    args[9]="misuse_keyword";
    args[10]="-t";
    args[11]="misuse_threshold";