public static void main(String[] args) {
    ArrayList<String> SPOquestions = new ArrayList<String>(); // adding the sports questions for the quiz
    //...
    ArrayList<String> MUSquestions = new ArrayList<String>(); // adding the music questions
    //...
    ArrayList<String> GENquestions = new ArrayList<String>(); // adding general knowledge questions
    //...
}