//...
    public ArrayList<Boolean> checkBoxesState;
    //...

    public mAdapter(Context context, ArrayList<String> posit, ArrayList<String> list, ArrayList<Boolean> checkBoxesState /* <- add this one*/) {
        //...
        this.checkBoxesState = checkBoxesState;
    }