room1 = new Room(1);
 room2 = new Room(2);
 room3 = new Room(3);
 room4 = new Room(4);
 room1.Addexits(room4,"West");
 room1.Addexits(room3,"East");
 room2.Addexits(room2,"North");
 room2.Addexits(room2,"South");
 room3.Addexits(room3,"West");
 room3.Addexits(room3,"East");
 room4.Addexits(room4,"West");
 room4.Addexits(room4,"East");