String Retrieve 
                    = "SELECT `o`.`order_id` , `o`.`betalingsKenmerk` , `o`.`betaalMethode` , `o`.`tijdstipBezorging` , `o`.`datum`"
                    + ", `o`.`adres` , `o`.`huisnummer` , `o`.`postcode` , `o`.`woonplaats` , `o`.`landCode` , `o`.`extrainfo` , `o`.`opmerking`"
                    + ", `o`.`altEmail` , `o`.`voornaam` , `o`.`achternaam` , `o`.`bedrijfsnaam` , `o`.`telnummer` , `o`.`betaald` , `o`.`bezorgkosten`"
                    + ", `o`.`totaalExBzg` , `o`.`siteCode` , `o`.`opmerking`"
                    + ", IF(`o`.`transactieID` = -1, 1,0) "
                    + "AS pickup, `r`.`rest_id`, TRIM(CONCAT(`r`.`naam`, ' ', `r`.`filiaal`)) AS restname"
                    + " FROM `thuis`.`order` o IGNORE INDEX(connectieid, doorberekenen)"
                    + "INNER JOIN `connectie` c IGNORE INDEX(methode)"
                    + "ON `o`.`connectieId` = `c`.`id`"
                    + "AND `c`.`methode` = 26 "
                    + "INNER JOIN `restaurant` `r`"
                    + "ON `o`.`restaurantRest_id` = `r`.`rest_id`"
                    + "WHERE `o`.`datum` >= TIMESTAMP(CURDATE())"
                    + "AND o.order_statusOrder_status_id = '1'"
                    + "AND o.order_statusOrder_device_id = ?"
                    + "AND o.doorberekenen = '1'"
                    + "AND ((o.bevestigingsId IS NULL OR o.bevestigingsId = 0) AND o.bevestigdDoor IS NULL)";