public class FruitPlant extends Plant {
    public static enum Type {
        // Dry-hot 
        PEACH_TREE("peach", 3, 80, Fruit.Type.PEACH),
        // ...
    }
    // ...
}

// ...
public class Fruit implements Element, Holdable, Plantable {
    public static enum Type {
        // ...
        PEACH(FruitPlant.Type.PEACH_TREE),
        // ...
    }
    // ...
}