TextView headerData1 =  new TextView(this);
    header1.setText("0350005000");
    header1.setLayoutParams(params);
    headerRowData.addView(headerData1);
    TextView headerData2 =  new TextView(this);
    header2.setText("Vendor_A");
    header2.setLayoutParams(params);
    headerRowData.addView(headerData2);
    TextView headerData3 =  new TextView(this);
    header3.setText("EUR");
    header3.setLayoutParams(params);
    headerRowData.addView(headerData3);
    TextView headerData4 =  new TextView(this);
    header4.setText("44.60");
    header4.setLayoutParams(params);
    headerRowData.addView(headerData4);