String str="TABLE 5L : ESTIMATED AREA UNDER OTHER aaaa TREATED WITH PSB BY SIZE GROUPS." +
            "TABLE 6L : ESTIMATED AREA UNDER OTHER bbbbb  TREATED WITH PSB BY SIZE GROUPS." +
            "TABLE 7L : ESTIMATED AREA UNDER OTHER ccccc TREATED WITH PSB BY SIZE GROUPS." +
            "TABLE 8L : ESTIMATED AREA UNDER OTHER dddddd  TREATED WITH PSB BY SIZE GROUPS." +
            "TABLE 9L : ESTIMATED AREA UNDER OTHER eeeee  TREATED WITH PSB BY SIZE GROUPS." +
            "TABLE 10L: ESTIMATED AREA UNDER OTHER ffffff  TREATED WITH PSB BY SIZE GROUPS." +
            "TABLE 11L: ESTIMATED AREA UNDER OTHER gggg  TREATED WITH PSB BY SIZE GROUPS." +
            "TABLE 12L: ESTIMATED AREA UNDER OTHER hhhh TREATED WITH PSB BY SIZE GROUPS." +
            "TABLE 13L: ESTIMATED AREA UNDER OTHER llll  TREATED WITH PSB BY SIZE GROUPS.";


    Pattern pattern = Pattern.compile("OTHER(.*?)TREATED");
    Matcher matcher = pattern.matcher(str);
    while (matcher.find()) {
        System.out.println(matcher.group(1));
    }