WebDriver driver = new ChromeDriver();
driver.manage().window().maximize();
driver.get("http://automationpractice.com/index.php");
Thread.sleep(2000);
driver.findElement(By.xpath(".//a[@class='login']")).click();
Thread.sleep(1000);
driver.findElement(By.xpath(".//input[@id='email_create']")).sendKeys("abc123_1@yahoo.com");
Thread.sleep(1000);
driver.findElement(By.xpath(".//button[@id='SubmitCreate']")).click();
Thread.sleep(4000);
driver.findElement(By.xpath(".//input[@id='id_gender1']")).click();
Thread.sleep(1000);