boolean runSortTest = false;
  println("1");
  runSortTest = runTest(url, "_results/a_insertion.txt", insertion);
  println("2");
  runSortTest = runTest(url, "_results/b_merge.txt", merge);
  println("3");
  //runSortTest = runTest(url, "_results/c_bubble.txt", bubble);
  println("4");
  runSortTest = runTest(url, "_results/d_shell.txt", shell);
  println("5");
  runSortTest = runTest(url, "_results/e_quickSort.txt", quickSort);
  println("6");