if (ball.getY() < getHeight()-HEIGHT/2 && ball.getY() > HEIGHT/2) { 
    ...
} else if (ball.getY() <= HEIGHT/2) { // note <= instead of <
    ...
} else { // ball.getY() >= getHeight()-HEIGHT/2
    ...
}