...
...
...

Intent intent1 = new Intent(EditNote.this, ViewNote.class);
                    intent1.putExtra("id", id);
                    intent1.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
                    startActivity(intent1);
                    //finish();
                }

...
...
...