@Override
public boolean onNavigationItemSelected(@NonNull MenuItem item) {
    switch (item.getItemId()) {
        case R.id.your_drawer_item_id:
            ....
            ....
        case R.id.your_drawer_item_id:
            ....
            ....
    }
}