public static void main(String[] args) {

    System.out.println("spring.profiles.active="+System.getProperty("spring.profiles.active"));
    ConfigurableApplicationContext ctx = SpringApplication.run(Application.class, args);
    System.out.println("Application Running!!!");

    autogenerateDatabaseTestdata(ctx);
}

private static void autogenerateDatabaseTestdata(ConfigurableApplicationContext ctx) {
    ctx.getBean(DataGenerator.class).run(ctx);
}