isBalanced("()[()]{([])}()[]");
 isBalanced("__[()]{([])}()[]");
  isBalanced("___()_{([])}()[]");
   isBalanced("______{([])}()[]");
    isBalanced("_______([])_()[]");
     isBalanced("________[]__()[]");
      isBalanced("____________()[]");
       isBalanced("______________[]");
        isBalanced("________________");