long previousFrameTime=System.currentTimeMillis();
while (running){
    .....
    .....
    long currentTime=System.currentTimeMillis();
    long frameTime=currentTime-previousFrameTime
    previousFrameTime=currentTime
    gamePanel.update(frameTime/1000.0);  //I personally like my frametimes in seconds, hence /1000.0, but thats up to you
    .....
    .....
 }