System.setProperty("webdriver.chrome.driver", "G:\\naveen\\mywork\\testing\\automation\\tools\\webdrivers\\chromedriver.exe");
    WebDriver driver = new FirefoxDriver();
    driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
    driver.get("http://stackoverflow.com");
    driver.manage().window().maximize();
    driver.findElement(By.id("nav-tags")).click();
    WebElement element = driver.findElement(By.name("tagfilter"));
    element.sendKeys("qa");
    Thread.sleep(2000);
    element.sendKeys(Keys.ENTER);
    Thread.sleep(3000);
    WebElement popularTag = driver.findElement(By.xpath("//table[@id='tags-browser']/tbody/tr[1]/td[1]/a"));
    System.out.println("most popular tag: " + popularTag.getText());
    WebElement populatTagCount = driver.findElement(By.xpath("//table[@id='tags-browser']/tbody/tr[1]/td[1]/span/span[2]"));
    System.out.println("popular tag count " + populatTagCount.getText());
    WebElement tagCountAnual = driver.findElement(By.xpath("//table[@id='tags-browser']/tbody/tr[1]/td[1]/div[2]/div[1]/a[2]"));
    System.out.println("anaual count : " + tagCountAnual.getText());
    int anaualCount = Integer.parseInt(tagCountAnual.getText().split(" ")[0]);
    System.out.println("count " + anaualCount);
    driver.close();