package com.bechirspace.testproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Person implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private com.bechirspace.testproject.data data;

    public Person() {
    }

    public com.bechirspace.testproject.data getData() {
        return this.data;
    }

    public void setData(com.bechirspace.testproject.data data) {
        this.data = data;
    }

    public Person(com.bechirspace.testproject.Data data) {
        this.data = data;
    }


}