final ExpressionParser parser = new SpelExpressionParser();
StandardEvaluationContext context = new StandardEvaluationContext();
context.addPropertyAccessor(new MapAccessor());
Expression expression = parser.parseExpression("expressionUtil.subtractDates(fromDate, toDate)");
Map<String, Object> map = new HashMap<>();
map.put("expressionUtil", new ExpressionUtil());
map.put("fromDate", new Date(System.currentTimeMillis()));
map.put("toDate", new Date(System.currentTimeMillis() + 1000));
Long value = expression.getValue(context, map, Long.class);
System.out.println(value);