[
    {
        "DoctorId": 3,
        "UserId": 0,
        "FirstName": "Nitish",
        "MiddleName": "",
        "LastName": "Rana",
        "Qualification": null,
        "Description": null,
        "Experience": null,
        "Email": "d@d.com",
        "Phone": "3245",
        "AddressId": 66,
        "LocationId": 51
    },
    {
        "DoctorId": 4,
        "UserId": 0,
        "FirstName": "Nitish ",
        "MiddleName": "",
        "LastName": "Rana",
        "Qualification": null,
        "Description": null,
        "Experience ": null,
        "Email": "d@d.com",
        "Phone": "3245",
        "AddressId": 67,
        "LocationId": 52
    },
    {
        "DoctorId ": 5,
        "UserId": 0,
        "FirstName": "Nitish",
        "MiddleName": "",
        "LastName": "Rana",
        "Qualification ": null,
        "Description": null,
        "Experience": null,
        "Email": "d@d.com",
        "Phone": "3245",
        "AddressId ": 68,
        "LocationId": 53
    },
    {
        "DoctorId": 6,
        "UserId": 0,
        "FirstName": "wefwe",
        "MiddleName ": "",
        "LastName": "rthyt",
        "Qualification": "",
        "Description": "",
        "Experience": "",
        "Email ": "w@w.com",
        "Phone": "43256",
        "AddressId": 69,
        "LocationId": 54
    },
    {
        "DoctorId": 7,
        "UserId ": 0,
        "FirstName": "dwefw",
        "MiddleName": "",
        "LastName": "tfhbede",
        "Qualification ": "",
        "Description": "",
        "Experience": "",
        "Email": "w@w.com",
        "Phone": "345",
        "AddressId ": 70,
        "LocationId": 55
    },
    {
        "DoctorId": 8,
        "UserId": 0,
        "FirstName": "ghnsfssw",
        "MiddleName ": "",
        "LastName": "fdvfd",
        "Qualification": "",
        "Description": "",
        "Experience": "",
        "Emai ": "w@w.com",
        "Phone": "3245",
        "AddressId": 71,
        "LocationId": 56
    },
    {
        "DoctorId": 9,
        "UserId ": 0,
        "FirstName": "csdcs",
        "MiddleName": "",
        "LastName": "dfvfgb",
        "Qualification ": "",
        "Description": "",
        "Experience": "",
        "Email": "q@a.com",
        "Phone": "34567",
        "AddressId ": 72,
        "LocationId": 57
    },
    {
        "DoctorId": 10,
        "UserId": 0,
        "FirstName": "regresrg",
        "MiddleName ": "",
        "LastName": "ukyt",
        "Qualification": "",
        "Description": "",
        "Experience": "",
        "Email ": "q@q.com",
        "Phone": "3242567",
        "AddressId": 73,
        "LocationId": 58
    },
    {
        "DoctorId": 11,
        "UserId ": 0,
        "FirstName": "fvger",
        "MiddleName": "",
        "LastName": "ujtyhr",
        "Qualification ": "",
        "Description": "",
        "Experience": "",
        "Email": "d@s.com",
        "Phone": "43567",
        "AddressId ": 74,
        "LocationId": 59
    },
    {
        "DoctorId": 12,
        "UserId": 0,
        "FirstName": "gfere",
        "MiddleName ": "",
        "LastName": "ergfe",
        "Qualification": "",
        "Description": "",
        "Experience": "",
        "Email ": "q@q.com",
        "Phone": "32465",
        "AddressId": 75,
        "LocationId": 60
    },
    {
        "DoctorId": 13,
        "UserId ": 0,
        "FirstName": "erfe",
        "MiddleName": "",
        "LastName": "rtghynu",
        "Qualification ": "",
        "Description": "",
        "Experience": "",
        "Email": "s@q.com",
        "Phone": "23456",
        "AddressId ": 76,
        "LocationId": 61
    },
    {
        "DoctorId": 15,
        "UserId": 0,
        "FirstName": "Nitish",
        "MiddleName ": "",
        "LastName": "Rana",
        "Qualification": null,
        "Description": null,
        "Experience": null,
        "Email ": "d@d.com",
        "Phone": "3245",
        "AddressId": 78,
        "LocationId": 63
    }
]