RandomCollection<String> randomCollection = 
    new RandomCollection<String>()
        .add(4,  "Task1")
        .add(10, "Task2")
        .add(15, "Task3")
        .add(1,  "Task4")
        .add(8,  "Task5")
        .add(3,  "Task6")
        .add(25, "Task7")
        .add(12, "Task8")
        .add(4,  "Task9")
        .add(12, "Task10")
        .add(12, "Task11")
        .add(10, "Task12")
        .add(12, "Task13")
        .add(20, "Task14")
        .add(12, "Task15")
        .add(12, "Task16");