public void saveInformation(InsuranceInformation insuranceInformation)
{       
    try
    {
        int noOfRowsAffected = getConnectionObject().getStatement().executeUpdate(
                "INSERT INTO sg_InsuranceInfo(Patient_Name,LIC_Name) VALUES(" + "'" + insuranceInformation.getPatientName() + "','" + insuranceInformation.getLicName() + "'"
                        + ")");
        if (noOfRowsAffected != 0)
        {
            ResultSet autoGeneratedId = getConnectionObject().getStatement().executeQuery("SELECT SCOPE_IDENTITY()");
            if(autoGeneratedId.next())
            {
                System.out.println(autoGeneratedId.getInt(1));
            }
        }
    }
    catch (SQLException e)
    {
        e.printStackTrace();
    }
}