int scale = 2;
double sum = BigDecimal.valueOf(Double.valueOf(sumText.getText()) / 12d).setScale(scale, BigDecimal.ROUND_HALF_UP).doubleValue();
                    part1Sum.setText(Double.toString(sum));
                    part2Sum.setText(Double.toString(sum));
                    part3Sum.setText(Double.toString(sum));
                    part4Sum.setText(Double.toString(sum));
                    part5Sum.setText(Double.toString(sum));
                    part6Sum.setText(Double.toString(sum));
                    part7Sum.setText(Double.toString(sum));
                    part8Sum.setText(Double.toString(sum));
                    part9Sum.setText(Double.toString(sum));
                    part10Sum.setText(Double.toString(sum));
                    part11Sum.setText(Double.toString(sum));
                    part12Sum.setText(Double.toString(sum));