CREATE OR REPLACE FUNCTION delete_room()
  RETURNS trigger AS
$BODY$
BEGIN
 DELETE FROM ROOMS WHERE (OLD.ROOM_ID = ID)
 RETURN NEW;
END;
$BODY$


CREATE TRIGGER delete_room_changed
  BEFORE UPDATE
  ON USERS
  FOR EACH ROW
  EXECUTE PROCEDURE delete_room()