Stack<Integer> stack = new Stack<Integer>();
stack.push(99);
stack.push(64);
stack.push(73);
stack.push(54);
stack.push(100);
stack.push(82);
stack.push(55);
stack.push(300);
System.out.println(minimalValue(stack));
System.out.println (stack);