NetworkSecurityGroup NSG = azure.networkSecurityGroups()
                    .define(networkSecurityGroup)
                    .withRegion(region)
                    .withExistingResourceGroup(resourceGroup)
                    .defineRule("Inbound")
                        .allowInbound()
                        .fromAnyAddress()
                        .fromAnyPort()
                        .toAnyAddress()
                        .toAnyPort()
                        .withAnyProtocol()
                        .withDescription("Incoming messsages")
                        .withPriority(100)
                        .attach()
                    .create();