public  static String  Buy_Price = "a";
public  static String  Sell_Price = "b";
public  static String  QUANTITY = "c";
public  static String  BROKERAGE = "d";
public  static String  ActualProfitLoss_String = "e";
public  static String  TurnOver_String = "f";
public  static String  STT_String = "g";
public  static String  ServiceTax_String = "h";
public  static String  TotalCharge_String = "i";
public  static String  x =  = "j";