enum {
     MEDIA_ERROR_BASE        = -1000,

     ERROR_ALREADY_CONNECTED = MEDIA_ERROR_BASE,
     ERROR_NOT_CONNECTED     = MEDIA_ERROR_BASE - 1,
     ERROR_UNKNOWN_HOST      = MEDIA_ERROR_BASE - 2,