@ActiveProfiles("test")
    @RunWith(SpringJUnit4ClassRunner.class)
    @SpringApplicationConfiguration(classes = MyApplication.class)
    @WebIntegrationTest
    public class MessageControllerTest {

        @Autowired
        MessageRepository messageRepository;
        ...
        ...
        ...
        @Test
        public void testSomething(){
        ...
        ...
        ...
        ...
        }
    }