...
import org.apache.poi.xddf.usermodel.chart.ChartTypes;
...
//XDDFChartData data = new XDDFPieChartData(chart.getCTChart().getPlotArea().addNewPieChart());
XDDFChartData data = chart.createData(ChartTypes.PIE, null, null);
...