ArrayList<Integer> possibles = new ArrayList <Integer>();
 int guess = 50; //my guess is generated by another method. Not listed here
 int tens = guess / 10 % 10;

 for (int x = 10; x < 100; x++) {
   if (x / 10 % 10 != tens) {
     possibles.add(x);
   } 
 }