private static final String CREATE_TABLE_QUESTION ="CREATE TABLE "
      + TABLE_QUESTION +" ( "
      + KEY_QUESTIONID +" INTEGER PRIMARY KEY, "
      + KEY_QUESTION + " TEXT , "
      + KEY_OPTIONA + " TEXT, "
      + KEY_OPTIONB + " TEXT, "
      + KEY_OPTIONC + " TEXT, "
      + KEY_ANSWER + " TEXT, "
      + KEY_LEVEL + " INTEGER, "
      + KEY_CATEGORYID + " INTEGER "+")";