InputStream inputStream;
BufferedInputStream bis;
try {
    inputStream = assetManager.open(from);
    bis = new BufferedInputStream(inputStream);
} catch (IOException e) {
...
...
try {
    outStream = new BufferedOutputStream(new FileOutputStream(file));
} catch (FileNotFoundException e) {
...
...
    while ((c = bis.read()) != -1) {
    ...
    }
...
...

bis.close();