JdbcStoreFactory objJSF = new JdbcStoreFactory(settings);
            JdbcLogFactory objJLF = new JdbcLogFactory(settings);
            SQLServerDataSource ds = new SQLServerDataSource();
            ds.setServerName(<SERVER_NAME);
            ds.setDatabaseName(<quickfix_database_name>);
            ds.setInstanceName(<INSTANCE_NAME>);               
          ds.setIntegratedSecurity(AUTHMODE.toUpperCase().contains("WINDOW") ? true : false);
            objJSF.setDataSource(ds);
            objJLF.setDataSource(ds);
            storeFactory = objJSF;
            logFactory = objJLF;
        MessageFactory messageFactory = new MessageFactory();
        initiator = new SocketInitiator(application, storeFactory, settings, logFactory, messageFactory);