JSONObject json=new JSONObject();
  json.put("method", "SearchBySearchConfiguration"); 
  JSONArray paramsArr = new JSONArray();
    JSONObject arrobj = new JSONOject();
      arrobj.put("SearchCriteria","%arriva");
      arrobj.put("IsAccountSearch","true");
      arrobj.put("IsContactSearch","false");
      arrobj.put("SearchByName","true");
      arrobj.put("SearchByAddress","false");
      arrobj.put("CRMTextValues",new JSONArray());
      arrobj.put("CRMCurrencyValues",new JSONArray());
    paramsArr.put(arrobj);
  json.put("params",paramsArr);