int[][] tester={{1,2},{3,4},{5,6},{7,8}};
    int row=2;
    int[][] testerCopy=new int[tester.length-1][tester[0].length];
    System.out.println(tester.length);
    System.arraycopy(tester, row+1, tester, row, tester.length-row-1);
    System.arraycopy(tester, 0, testerCopy, 0, testerCopy.length);
    System.out.println(Arrays.toString(testerCopy[0]));
    System.out.println(Arrays.toString(testerCopy[1]));
    System.out.println(Arrays.toString(testerCopy[2]));
    System.out.println(testerCopy.length);