private static String check (String str, Wrapper wrapper) { 
        ...
        ...
        if (input[0].contains("EX")) {
           wrapper.setPoints(Integer.parseInt(input[1]));
           wrapper.setAttempts(Integer.parseInt(input[2]));
           wrapper.setCorrect(Integer.parseInt(input[3]));
           return "EX";
        }
        ...
        ...
}