private String jString = "{"
+ "    \"geodata\": ["
+ "        {"
+ "                \"id\": \"1\","
+ "                \"name\": \"Jenifer Hathway\","
+ "                \"email\": \"jh@gmail.com\","
+ "                \"address\": \"xx-xx-xxxx,x - street, x - country\","
+ "                \"gender\" : \"female\","
+ "                \"latitude\" : \"37.33774833333334\","
+ "                \"longitude\" : \"-121.88670166666667\","
+ "                \"phone\": {"
+ "                    \"mobile\": \"+91 0000000000\","
+ "                    \"home\": \"00 000000\","
+ "                    \"office\": \"00 000000\""
+ "                }"
+ "        },"
+ "        {"
+ "                \"id\": \"2\","
+ "                \"name\": \"Johnny Depp\","
+ "                \"email\": \"johnny_depp@gmail.com\","
+ "                \"address\": \"xx-xx-xxxx,x - street, x - country\","
+ "                \"gender\" : \"male\","
+ "                \"latitude\" : \"37.336453\","
+ "                \"longitude\" : \"-121.884985\","
+ "                \"phone\": {"
+ "                    \"mobile\": \"+91 0000000000\","
+ "                    \"home\": \"00 000000\","
+ "                    \"office\": \"00 000000\""
+ "                }"
+ "        }"
+ "    ]"
+ "}";