PrintWriter writer = new PrintWriter("textFieldOutput.txt", "UTF-8");
writer.println("First text field:");
writer.println(textField1Val);
writer.println("Second text field:");
writer.println(textField2Val);
writer.println("Third text field:");
writer.println(textField3Val);
writer.println("Fourth text field:");
writer.println(textField4Val);
writer.println("Fifth text field:");
writer.println(textField5Val);
writer.println("Sixth text field:");
writer.println(textField6Val);
writer.println("Seventh text field:");
writer.println(textField7Val);
writer.close();