System.out.println("Menu Choices: ");
    System.out.println("1. List All Movies Available");
    System.out.println("2. List All Customers From Rental Database");
    System.out.println("3. Add a New Movie To List");
    System.out.println("4. Enroll a New Member");
    System.out.println("5. Search Movies");
    System.out.println("6. Delete Movies From Store");
    System.out.println("7. Search For A Member ");
    System.out.println("8. Quit.");
    System.out.println();
    System.out.print("Enter your choice: ");
    a = input.nextInt();  
    System.out.println();