DROP TABLE IF EXISTS REGIONAL_AREA1_REGIONAL_AREA2;
DROP TABLE IF EXISTS REGIONAL_AREA1_REGIONAL_AREA2;

CREATE TABLE REGIONAL_AREA1_REGIONAL_AREA2(
    REGIONAL_AREA1 VARCHAR(36) NOT NULL,
    REGIONAL_AREA2 VARCHAR(36) NOT NULL
);  

CREATE TABLE REGIONAL_COUNTRY_REGIONAL_AREA1(
    REGIONAL_COUNTRY VARCHAR(36) NOT NULL,
    REGIONAL_AREA1 VARCHAR(36) NOT NULL
);