btnExecute.setOnClickListener(new View.OnClickListener() { ... 
    public void onClick(View arg0) { ...
        if (((m1ssspinner.getSelectedItem() == "Square"))) { ...
            if (((m1ssspinner.getSelectedItem() == "Rectangle"))) { ...            
            if (((m1ssspinner.getSelectedItem() == "Circle"))) { ...
            if (((m1ssspinner.getSelectedItem() == "Elliptical"))) { ...