grails.project.fork = [
test       : [... useSplitVerifier: true ...],
]
...
grails.project.dependency.resolution = {
...
    dependencies {
        ...
        test ("org.spockframework:spock-core:1.1-groovy-2.3")
        ...
    }
...
}