...
@GET
@Path("customers/{customer-id}/orders/{order-id}/lineitems/{lineitem-id}")
public Response get(@PathParam("customer-id") String customerId, @PathParam("order-id") String orderId, @PathParam("lineitem-id") String lineItemId) {
    // fetch logic goes here...
}
...