....
    ....
    adapter.setOnItemLongClickListener(new RecyclerViewAdapter.OnItemLongClickListener() {
        @Override
        public void onItemLongClick(Entries entries) {
            entry = entries;  // this is very important, entry holds the current edited item
            Intent intent = new Intent(MainActivity.this, AddEditEntry.class);
            intent.putExtra(AddEditEntry.EXTRA_USERNAME, entry.getUsername());
            intent.putExtra(AddEditEntry.EXTRA_HINT, entry.getHint());
            intent.putExtra(AddEditEntry.EXTRA_PASSWORD, entry.getPassword());
            // no need to pass the id, it's a autogenerated field 
            // intent.putExtra(AddEditEntry.EXTRA_ID, entry.getId());
            startActivityForResult(intent, EDIT_ENTRY_REQUEST);
        }
    });

    ....
    ...

    @Override
    protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {

        if(requestCode == ADD_ENTRY_REQUEST && resultCode == RESULT_OK){
            ...
            ... 
        } else if(requestCode == EDIT_ENTRY_REQUEST && resultCode == RESULT_OK) {
            // in an Edit operation, id should not be modified, so, no need to pass this parameter 
            // int id = 
            // Objects.requireNonNull(data).getIntExtra(AddEditEntry.EXTRA_ID, -1);
            String username = Objects.requireNonNull(data).getStringExtra(AddEditEntry.EXTRA_USERNAME);
            String password = Objects.requireNonNull(data).getStringExtra(AddEditEntry.EXTRA_PASSWORD);
            String hint = Objects.requireNonNull(data).getStringExtra(AddEditEntry.EXTRA_HINT);

            // entry already exists, so, no need to create a new one            
            //Entries entry = new Entries(username, hint, password);
            //entry.setId(id);
            entry.setUsername(username);
            entry.setPassword(password);
            entry.setHint(hint);
            viewModel.update(entry);

            Toast.makeText(this, "Entry updated", Toast.LENGTH_SHORT).show();

        } else {
            Toast.makeText(this, "Entry not added!", Toast.LENGTH_SHORT).show();
        }
        super.onActivityResult(requestCode, resultCode, data);
    }