public void paint ( Graphics g2 ) {
    // Let's ignore the fact that you haven't called super.paint here...
    //code making dots up here...
    int a;
    if ( !stop ) {
        // Block the EDT, stop all painting and event processing until this for
        // exist...
        for ( a=0; a<delay; a++ ) ; 
        moveDot ( ) ;  
    }
    // This is a very bad idea inside any paint method...
    repaint();
}