PreparedStatement ps = connection.prepareStatement("insert into cars values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
ps.setInt(1, 1);
ps.setString(2, "car");
ps.setString(3, "Ford");
ps.setString(4, "Crown_Victoria");
ps.setInt(5, 2010);
ps.setString(6, "7/3/2012");
ps.setString(7, "7/23/2012");
ps.setInt(8, 8900);
ps.setInt(9, 4);