Properties props = new Properties();
props.setProperty("http.proxySet", "true");
props.setProperty("http.proxyHost", proxyHost);
props.setProperty("http.proxyPort", proxyPort);
props.setProperty("mail.imap.port", "993");
props.setProperty("mail.store.protocol", "imaps");
Session session = Session.getInstance(props, null);
Store store = session.getStore("imaps");
store.connect("imap.gmail.com", email, pass);
Folder inbox = store.getFolder("INBOX");
inbox.open(Folder.READ_ONLY);