...
PieChart pie = new PieChart(createTable(), createOptions());
...
private Options createOptions() {
  Options options = Options.create();
...
  options.setEnableTooltip(false);
  return options;
}
...