public class Gui {
    ...
    JPanel cards = ne JPanel(new CardLayout());
    private void initComponetns() {
        ...
        // cards to be the container with CardLayout...
        cards.add(new PanelA(this));
        cards.add(new PanelB(this));
        ...
    }
}