{
 "name1":"value1",
 "name2":"value2",
  "name3":[
         {
          "ComponentId":"qwer",
          "InstanceId":"amba"
         },
         {
          "ComponentId":"qwer",
          "InstanceId":"coramba"
         },
         {
          "ComponentId":"dsa",
          "InstanceId":"badar"
         },
         {
          "ComponentId":"dsa",
          "InstanceId":"fdarr"
         },
         {
          "ComponentId":"dsa",
          "InstanceId":"sdddd"
         }
         ]
}