CREATE_USERNAMEPASSWORD_TABLE = "CREATE TABLE "+ TABLE_UsernamePassword + "("
+ USERNAMEPASSWORD_ID + " INTEGER PRIMARY KEY AUTOINCREMENT," 
+ USERNAMEPASSWORD_KEY_WEBTITLE + " TEXT,"
+ USERNAMEPASSWORD_KEY_WEBPASSWORD + " TEXT,"
+ USERNAMEPASSWORD_KEY_WEBNAME+" TEXT,"
+ USERNAMEPASSWORD_KEY_WEBURL +" TEXT,"
+ USERNAMEPASSWORD_KEY_WEBTYPE + " TEXT,"
+ USERNAMEPASSWORD_KEY_WEBIMAGE + " INTEGER"+");";