attachments = new MimeBodyPart(); 
DataSource source = new FileDataSource(dest); 
attachments.setDataHandler(new DataHandler(source)); 
attachments.setFileName(source.getName());
mp.addBodyPart(attachments); 
Multipart htmlAndTextMultipart = new MimeMultipart("alternative"); 
MimeBodyPart htmlBodyPart = new MimeBodyPart();
htmlBodyPart.setContent(body, "text/html; charset=utf-8");
htmlAndTextMultipart.addBodyPart(htmlBodyPart); 
MimeBodyPart htmlAndTextBodyPart = new MimeBodyPart(); 
htmlAndTextBodyPart.setContent(htmlAndTextMultipart); 
mp.addBodyPart(htmlAndTextBodyPart);