@DynamoDBAutoGenerated(generator=AutoGeneratedTimestampWithOffset.Generator.class)
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.METHOD})
public @interface AutoGeneratedTimestampWithOffset {

    /**
     * See {@link ZoneOffset#of(String)} for valid values.
     */
    String offset();
    DynamoDBAutoGenerateStrategy strategy() default DynamoDBAutoGenerateStrategy.ALWAYS;

    public class Generator implements DynamoDBAutoGenerator<String> {
        private final String offset;
        private final DynamoDBAutoGenerateStrategy strategy;

        public Generator(final Class<String> targetType, final AutoGeneratedTimestampWithOffset annotation) {
            this.offset = annotation.offset();
            this.strategy = annotation.strategy();
        }

        @Override
        public DynamoDBAutoGenerateStrategy getGenerateStrategy() {
            return strategy;
        }

        @Override
        public final String generate(final String currentValue) {
            return OffsetDateTime.ofInstant(Instant.now(), ZoneOffset.of(offset)).toString();
        }
    }
}