Statement stmt = connection.createStatement();
stmt.executeUpdate("CREATE TABLE tblclientes (_id INTEGER, Nombres TEXT, Apellidos TEXT, RazSocial TEXT, Direccion TEXT, Ciudad TEXT DEFAULT 'Arequipa', Fono TEXT, Fax TEXT, Email TEXT, Ruc TEXT, latitud FLOAT, longitud FLOAT, ruta TEXT, sincro TEXT, copiar INT DEFAULT 1)");
PreparedStatement ins = connection.prepareStatement("INSERT INTO tblclientes VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
connection.setAutoCommit(false);
for(...i...) {
    ins.clearParameters();
    ins.setInt(1, id[i]); //1, 2, ...
    ins.setString(2, nombre[i]); //"Julia", ...
    ins.setString(3, apellidos[i]); //"Lea Barrios", ...
    ...
    ins.setDouble(11, latitud[i]); //-16,34930944346466, ...
    ins.setDouble(12, longitud[i]); //-71,56028982646531, ...
    ...
    ins.setInt(15, copiar[i]); //1, ...
    ins.execute();
}
connection.commit(); //All inserts are done now, at once!
connection.setAutoCommit(true); //restore autocommit