public static final String IMAGE_RES_ID = "image_res_id";
private Intent intent = new Intent(SelectDesign.this, GarmentEntry.class);
   ....
   ....
   ....
   CocktailHenButton.setOnClick(
       ....
       intent.putExtra(IMAGE_RES_ID, R.drawable.cocktailhen);
       startActivity(intent);
   }

   ValueHenButon.setOnClick(
        ....
        intent.putExtra(IMAGE_RES_ID, R.drawable.valuehen);
        startActivity(intent);