String req="UPDATE `fos_user`
        set `addressmailperso` = ? 
        ,`pays`  = ? 
        ,`job` =? 
        ,`sexe` = ? 
        , `addressjob` =?
        ,`skills` = ? 
        ,`description` =? 
  WHERE username='"+Apptest.current+"';";