ScriptlessBody ::= ( ( ‘<%--’ JSPCommentBody )
                   | ( ‘<%@’ DirectiveBody )
                   | ( ‘<jsp:directive.’ XMLDirectiveBody )
                   | ( ‘<%!’ <TRANSLATION_ERROR> )
                   | ( ‘<jsp:declaration’ <TRANSLATION_ERROR> )
                   | ( ‘<%=’ <TRANSLATION_ERROR> )
                   | ( ‘<jsp:expression’ <TRANSLATION_ERROR> )
                   | ( ‘<%’ <TRANSLATION_ERROR> )
                   | ( ‘<jsp:scriptlet’ <TRANSLATION_ERROR> )
                   | ( ‘${‘ ELExpressionBody )
                   | ( ‘#{‘ ELExpressionBody )
                   | ( ‘<jsp:text’ XMLTemplateText )
                   | ( ‘<jsp:’ StandardAction )
                   ( ( ‘</’ ExtraClosingTag )
                   | ( ‘<‘ CustomAction CustomActionBody )
                   | TemplateText
                   )*