JButton btncarp = new JButton("*");  <---- your button name is btncarp
    ....
    ....
    btn0.addActionListener(new ActionListener() { <----you add action listener to btn0?!!!
        public void actionPerformed(ActionEvent e) {
            ......
            ......
        }
    });