Scanner scan = new Scanner (System.in);

    int randomValue = 0;   //this is the random value that'd be autogenerated in each loop
    int counter = 1;    //this represents the number of trials

    System.out.println("how many dice dots do u want?");
    int dotsWanted = scan.nextInt();

    while(randomValue != dotsWanted){
        randomValue = (int) (6 * Math.random()) + 1;
        counter++;
    }

    System.out.printf("In %d trials, %d dots were found\n", counter, dotsWanted);