String location = "C:\\Windows\\System32\\javaw.exe";
String p1="-cp"; 
String p2="jts.jar;total.2012.jar"; 
String p3="-Dsun.java2d.noddraw=true";
String p4="-Dswing.boldMetal=false";
String p5="-Dsun.locale.formatasdefault=true";
String p6="-Xmx768M";
String p7="-XX:MaxPermSize=128M";
String p8="jclient/LoginFrame" ;
String p9 = "C:\\Jts";