JScrollPane consoleScrollPane = new JScrollPane(console);
//...
// Add the scroll pane...
getContentPane().add(consoleScrollPane);
// Add the console, which WAS on the scrollpane to the content pane
getContentPane().add(console);