@RELATION yourTable

@ATTRIBUTE Amount-F1 NUMERIC
@ATTRIBUTE Time-F1 NUMERIC
@ATTRIBUTE Amount-F2 NUMERIC
@ATTRIBUTE Time-F2 NUMERIC
@ATTRIBUTE Amount-F3 NUMERIC
@ATTRIBUTE Time-F3 NUMERIC
...
@ATTRIBUTE Class {1,2,3} % your class labels

@DATA
50, 10, 20, 10, 1
20, 2, 100, 20, 3
...