...

libraryDependencies ++= {
  ...
  Seq(
    ...
    "org.eclipse.jetty" % "jetty-webapp"        % "8.1.17.v20150415"  % "container,test,compile",
    "org.eclipse.jetty.orbit" % "javax.servlet" % "3.0.0.v201112011016" % "container,test,compile" artifacts Artifact("javax.servlet", "jar", "jar"),
    ...

  )
}

...