@Test
public void testXML() {
    final String s = "<?xml version=\"1.0\" encoding=\"UTF-8\"?><results>\n" +
            "    <status>OK</status>\n" +
            "    <usage>By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html</usage>\n" +
            "    <url/>\n" +
            "    <language>english</language>\n" +
            "    <docSentiment>\n" +
            "        <type>neutral</type>\n" +
            "    </docSentiment>\n" +
            "</results>";

    DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
    DocumentBuilder builder;
    try
    {
        builder = factory.newDocumentBuilder();
        Document doc = builder.parse( new InputSource( new StringReader( s ) ) );

        XPathFactory xPathfactory = XPathFactory.newInstance();
        XPath xpath = xPathfactory.newXPath();
        XPathExpression expr = xpath.compile("//docSentiment/type");
        NodeList nl = (NodeList) expr.evaluate(doc, XPathConstants.NODESET);
        System.out.println("Sentiment:" + ((DTMNodeList) nl).getDTMIterator().toString());
    } catch (Exception e) {
        e.printStackTrace();
    }
}