...
public void getEntityById(Long id)
{
    ...
    if(id == null)
    {
       throw new BusinessRelatedConventionCompliantException(
                1,4,TYPE.CORE_BUSINESS,"Entity id can not be null"); 
        ...
    }
    ...
}