{
"devices": [
    {
        "name": "not set",
        "node": 1,
        "zone": 0,
        "type": "Portable Remote Controller",
        "internalType": "controller",
        "manufName": "undefined",
        "productName": "",
        "uuid": "413e3621-f4eb-4469-b986-78699455541c",
        "status": "Listening",
        "source": "zwave",
        "internalName": "zwave/controller/1",
        "values": {
            "Basic": "0"
        }
    },
    {
        "name": "not set",
        "node": 4,
        "zone": 0,
        "type": "Routing Binary Sensor",
        "internalType": "binarysensor",
        "manufName": "undefined",
        "productName": "",
        "uuid": "0dd6743c-6250-4cda-ab5c-871844090642",
        "status": "Sleeping",
        "source": "zwave",
        "internalName": "zwave/binarysensor/4",
        "values": {
            "Sensor": "false",
            "Wake-up Interval": "3600"
        }
    },
    {
        "name": "not set",
        "node": 3,
        "zone": 0,
        "type": "Multilevel Power Switch",
        "internalType": "dimmer",
        "manufName": "FIBARO System",
        "productName": "FGD211 Universal Dimmer 500W",
        "uuid": "c00228e5-45cc-4ac4-8371-9ac179857926",
        "status": "Listening",
        "source": "zwave",
        "internalName": "zwave/dimmer/3",
        "values": {
            "Timeout": "0",
            "1. Enable/Disable ALL ON/OFF": "null",
            "20. ADVANCED Impulse length": "110",
            "Frame Count": "0",
            "17. 3-way switch": "null",
            "8. Dimming step at automatic control": "1",
            "Report": "null",
            "Protocol Version": "3.34",
            "Application Version": "1.06",
            "Test": "null",
            "13. Minimum dimmer level control": "2",
            "10. Time of AUTOMATIC moving between the extreme dimming values": "1",
            "Test Powerlevel": "null",
            "Start Level": "0",
            "Bright": "null",
            "Library Version": "3",
            "12. Maximum dimmer level control": "99",
            "16. Saving state before power faillure": "null",
            "Test Node": "0",
            "39. ALARM FLASHING alarm time": "600",
            "14. Inputs Button/Switch configuration": "null",
            "Dim": "null",
            "18. Synchronizing light level for associated devices": "null",
            "7. Control key #2 behaviour": "null",
            "11. Dimming step at manual control": "1",
            "15. Double click option": "null",
            "30. Alarm": "null",
            "9. Time of MANUALLY moving between the extreme dimming values": "5",
            "Powerlevel": "null",
            "19. Change [On-Off] bi-stable keys": "null",
            "Test Status": "null",
            "Ignore Start Level": "true",
            "Level": "99",
            "Set Powerlevel": "null",
            "Switch All": "null",
            "6. Separation of association sending (key 1)": "null",
            "Acked Frames": "64"
        }
    },
    {
        "name": "not set",
        "node": 2,
        "zone": 0,
        "type": "Routing Alarm Sensor",
        "internalType": "alarmsensor",
        "manufName": "undefined",
        "productName": "",
        "uuid": "1588357d-fdf0-4813-b447-10158a72be80",
        "status": "Sleeping",
        "source": "zwave",
        "internalName": "zwave/alarmsensor/2",
        "values": {
            "Application Version": "Unknown",
            "Alarm Type": "0",
            "Battery Level": "100",
            "Wake-up Interval": "3600",
            "Protocol Version": "Unknown",
            "Alarm Level": "0",
            "Library Version": "Unknown"
        }
    }
]  }