...
  if(x == palindromeList.length) break;
  palindromeList[x++] = String.valueOf(digit1) + String.valueOf(digit2) + ...
}
for(int i = 0; i < x; i++)
   System.out.println(i + "\t" + palindromeList[i]);
...