public static void main(String[] args) {

    final int MAX = 3;
    int randomNumber = 0;
    int userChoice = 0;
    int computerChoice = 0;
    int choice = 0;
    int rounds = 0;
    int lose = 0;
    int win = 0;
    int tie = 0;
    int computerScore = 0;
    int userScore = 0;
    Scanner input = new Scanner(System.in);
    Random rand = new Random();//random number generated by computer
    String str, another = "y";

    userChoice = 0;

    while (another.equalsIgnoreCase("y")) {// allows y or Y
        System.out.print("enter 1= rock 2= paper 3 = scissor(0 to quit):");
        rounds++;
        userChoice = Integer.parseInt(input.nextLine());

        if(userChoice == 0){
            System.out.print("Do you want to play again (y/n)? ");
            another = input.nextLine();
        } else if (userChoice > 0 && userChoice < 4){
            computerChoice = rand.nextInt(MAX) + 1;
            System.out.println("computer picked " + computerChoice);

            if (userChoice == computerChoice) {
                System.out.println("Tie Game!");
                System.out.println();
                tie++;
            } else if (userChoice == 1) {

                if (computerChoice == 2) {
                    //rock is covered by paper
                    System.out.println("  you lose");
                    lose++;
                    computerScore++;
                } else if (computerChoice == 3) {
                    //rock smashes scissors
                    System.out.println("  you win");
                    win++;
                    userScore++;
                }
            } else if (userChoice == 2) {
                if (computerChoice == 3) {
                    //paper is cut by scissors
                    System.out.println("  you lose");
                    lose++;
                    computerScore++;
                } else if (computerChoice == 1) {
                    //paper covers rock
                    System.out.println("  you win");
                    win++;
                    userScore++;
                }
            } else if (userChoice == 3) {

                if (computerChoice == 1) {
                    //scissors are smashed by rock
                    System.out.println("  you lose");
                    lose++;
                    computerScore++;
                } else if (computerChoice == 2) {
                    //scissors cut paper
                    System.out.println("  you win");
                    win++;
                    userScore++;
                }
            }
        }else{
            System.out.println("invalid number");
        }
        System.out.println("computer score: " + computerScore + " You Score: " + userScore + " Rounds: " + rounds+"\n");
    }
 }