HashMap<String,Object> Map1 = new HashMap<>();
    HashMap<String, HashMap<String,Object>> fileNameConstrains = new HashMap<>();
    Map1.put("A", 10);
    Map1.put("B", 20);
    fileNameConstrains.put("File1", Map1);
    Map1 = new HashMap<String,Object>();
    Map1.put("A", 10);
    Map1.put("B", 50);
    fileNameConstrains.put("File2", Map1);
    Map1 = new HashMap<String,Object>();
    Map1.put("A", 10);
    Map1.put("B", 60);
    fileNameConstrains.put("File3", Map1);