public class MainActivity extends ActionBarActivity {
    String outputFile = "test.3gp";
    private MediaRecorder myAudioRecorder;  // Your class variable: OK...
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        ...
        // MediaRecorder myAudioRecorder = new MediaRecorder();  // DELETE THIS LINE!!!
        myAudioRecorder = new MediaRecorder();  // OK...
        ...