{
  "12-09-19":[
    {
      "Country":"Bangladesh",
      "Profession":"X",
      "Salary":"100"
    },
    {
      "Country":"Bangladesh",
      "Profession":"Y",
      "Salary":"101"
    },
    {
      "Country":"Bangladesh",
      "Profession":"Z",
      "Salary":"102"
    }
  ],
  "11-09-19":[
    {
      "Country":"India",
      "Profession":"I",
      "Salary":"103"
    },
    {
      "Country":"India",
      "Profession":"J",
      "Salary":"104"
    }
  ],
  "10-09-19":[
    {
      "Country":"Nepal",
      "Profession":"N",
      "Salary":"105"
    },
    {
      "Country":"Nepal",
      "Profession":"M",
      "Salary":"106"
    }
  ]
}