Connection con;
    String url="jdbc:mysql://localhost/mydb";
    Class.forName("com.mysql.jdbc.Driver").newInstance();
    con=(Connection) DriverManager.getConnection(url,"root","");
    JasperReport jasperReport = JasperCompileManager.compileReport(fileName);
    JasperPrint print = JasperFillManager.fillReport(jasperReport, parameter, con);
    print.setPageHeight(100);
    print.setPageWidth(80);
    print.setOrientation(jasperReport.getOrientationValue().LANDSCAPE);
    JasperPrintManager.printReport(print,false);