Integer searchValue;
if ((searchValue = checkPerfectMatch(searchTerm)) != null) {
  // ...
} else if ((searchValue = checkGoodMatch(searchTerm)) != null) {
  // ...
} else if ((searchValue = checkHalfMatch(searchTerm)) != null) {
  // ...
}