//            Monitor serializedMonitorSource = MonitorFactory.start("serializedMonitor");
        Date measuringStartOriginal = new Date();
        byte[] serialized = serialize( measuringStartOriginal );
        Thread.sleep(100+i);
//            Monitor serializedMonitorDestination = (Monitor)deserialize( serialized );
        Date measuringStartDeserialized = (Date)deserialize( serialized );
//            serializedMonitorDestination.stop();
        Date measuringEnd = (new Date());
        long timeDifference =  measuringEnd.getTime() - measuringStartDeserialized.getTime();
        MonitorFactory.add( "timeDifference", "ms", timeDifference );