Query q = sessionFactory.getCurrentSession().createQuery(
        "SELECT tag.tag, "
                + " (SELECT count(*) as interestedCount FROM YpUserTag yut"
                + " INNER JOIN yut.ypTag yt"
                + " WHERE tag.id=yt.id"
                + " GROUP BY yt.id) as interestedCount, "
                + " (SELECT count(*) as promotionCount FROM YpPromotionTag ypt"
                + " INNER JOIN ypt.ypTag yt"
                + " WHERE tag.id=yt.id"
                + " GROUP BY yt.id) as promotionCount, "
                + " (SELECT count(*) as viewsCount FROM YpPromotionTag ypt"
                + " INNER JOIN ypt.ypTag yt"
                + " INNER JOIN ypt.ypPromotion.ypUserPromos yup"
                + " WHERE tag.id=yt.id"
                + " AND action='ACTION_VIEW'"
                + " GROUP BY yt.id) as viewsCount"                      
        + " FROM YpTag tag"
        + " ORDER BY tag.tag"
        );