...
Workbook workbook = ...
DataFormat dataFormat = workbook.createDataFormat();
...
... {
 Cell cell = ...
 ...
 CellUtil.setCellStyleProperty(cell, CellUtil.DATA_FORMAT, dataFormat.getFormat("#,##0.00"));
 ...
}
...