{
    "ASF_Service_ResponseVO":{
        "server_info":{
            "content":"onboardingv2serv:start_onboarding_session&CalThreadId=85&TopLevelTxnStartTime=13b40fe91c4&Host=L-BLR-00438534&pid=3564",
            "type":"String"
        },
        "id":"1",
        "result":{
            "id":"2",
            "typesig":"fff96cab366a5def",
            "onboarding_id":{
                "content":"137",
                "type":"String"
            },
            "type":"Onboarding::StartOnboardingSessionResponse",
            "success":{
                "content":"true",
                "type":"bool"
            }
        },
        "operation":{
            "content":"start_onboarding_session",
            "type":"String"
        },
        "requested_version":{
            "content":"1.0",
            "type":"String"
        },
        "typesig":"155c0afe34b",
        "service":{
            "content":"OnboardingV2",
            "type":"String"
        },
        "actual_version":{
            "content":"1.0",
            "type":"String"
        }
    }
}