MyObjects mos = new MyObjects();
MyObject mo1 = new MyObject();
mo1.setValue("34");
Set set1 = new Set();
set1.setVarName("age");
set1.setValue("String");
mo1.getSet().add(set1);
Set set2 = new Set();
set2.setVarName("name");
set2.setValue("String");
mo1.getSet().add(set2);
mos.getMyObject().add(mo1);
MyObject mo2 = new MyObject();
mo2.setValue("345");
Set set3 = new Set();
set3.setVarName("age");
set3.setValue("String");
mo2.getSet().add(set3);
Set set4 = new Set();
set4.setVarName("name");
set4.setValue("String");
mo2.getSet().add(set4);
mos.getMyObject().add(mo2);