String sql = "LOAD DATA "
        + " LOCAL INFILE '/Dataset/"+listOfFiles[i].getName()+".txt'"
        + "    INTO TABLE data "
        + "    CHARACTER SET utf8 "
        + "    FIELDS "
        + "        TERMINATED BY '|' "
        + "    LINES "
        + "    STARTING BY 'status' "
        + "        TERMINATED BY '\\n' "
        + "    (@col_type, @col_origin, @col_text, @col_url, @col_id, @col_time, @col_retcount)"
        + "     set userid = '1234' "
        + "      , original = @col_origin "
        + "      , datatext = @col_text "
        + "      , url = @col_url "
        + "      , id = @col_id "
        + "      , retcount = @col_retcount "
        + "      , date = str_to_date(@col_time, '%m/%d/%Y') "
        + "      , isanswer = CASE WHEN @col_origin LIKE '% abcd %' THEN 1 ELSE 0 END ";