if (row < 4 && num >= 100 * (the_frame[row + 1][column])) {
    ...
} else if (column < 4 && num >= 100 * (the_frame[row][column + 1])) {
    ...
} else if (row > 0 && num >= 100 * (the_frame[row - 1][column])) {
    ...
} else if (column > 0 && num >= 100 * (the_frame[row][column - 1])) {
    ...