Map<Integer, Integer> operationToStationMapping = new HashMap<>();
    operationToStationMapping.put(2,0);
    operationToStationMapping.put(7,0);
    operationToStationMapping.put(3,2);
    operationToStationMapping.put(9,2);
    operationToStationMapping.put(1,2);
    operationToStationMapping.put(5,5);
    operationToStationMapping.put(6,7);
    operationToStationMapping.put(8,-1);
    operationToStationMapping.put(10,-1);