generator.writeStartObject()
    .writeStartArray("rows")
        .writeStartObject()
            .writeStartObject("object")
                .write("id", "1")
            .writeEnd()
            .writeStartArray("values")
                .write("111")
                .write("reg text")
                .write("11")
            .writeEnd()
        .writeEnd()
    .writeEnd()
.writeEnd();