if (needOil) { // If needOil is equal to true... 
    // do stuff...
} else { // otherwise...
    // do another stuff... 
} 

if (needCleaning) {
    // do stuff...
} else {
    // do another stuff...
}