/**
 *
 * @author Ryan
 */
public class Test extends javax.swing.JPanel {

    private BufferedImage image;
    int width;
    int height;

    /**
     * Creates new form test
     */
    public Test() {
        try {
            image = ImageIO.read(new URL("http://imgs.mi9.com/uploads/flower/4533/tulip-flowers_400x300_80023.jpg"));
            invertImage();
        } catch (Exception e) {
        }
    }

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.drawImage(image, 0, 0, width, height, Color.black, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 400, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 300, Short.MAX_VALUE));
    }// </editor-fold>
    // Variables declaration - do not modify
    // End of variables declaration

    private void invertImage() {
        width = image.getWidth();
        height = image.getHeight();
        for (int x = 0; x < width; x++) {
            for (int y = 0; y < height; y++) {
                int color = image.getRGB(x, y);
                int red = Colors.red(color);
                int green = Colors.green(color);
                int blue = Colors.blue(color);

                int rgb = Colors.rgba(255 - red, 255 - green, 255 - blue);
                image.setRGB(x, y, rgb);
            }
        }
    }
}