SELECT CAR.ID AS ID, CAR.NAME AS NAME, CAT.ID AS CATEGORY_ID, 
       CAT.NAME AS CATEGORY_NAME, C.ID AS CITY_ID, C.NAME AS CITY_NAME,
FROM CARS CAR JOIN      
     CATEGORY CAT
     ON CAR.CATEGORY_ID = CAT.ID JOIN
     CITY C
     ON D.CITY_ID = C.ID
WHERE LOWER(CAR.NAME) LIKE CONCAT('%', LOWER(?), '%')
ORDER BY CAT.NAME, CAR.NAME;