ArrayList<Timer> timerlist1 = new ArrayList<Timer>();
    LocalDateTime current = LocalDateTime.now();
    Timer time1 = new Timer(current,45);
    System.out.println(time1.getFormattedTime(time1));
    Timer time2 = time1.getNextTimer(time1);
    System.out.println(time2.getFormattedTime(time2));
    Timer time3 = time2.getNextTimer(time2);
    System.out.println(time3.getFormattedTime(time3));
    Timer time4 = time3.getNextTimer(time3);
    System.out.println(time4.getFormattedTime(time4));
    Timer time5 = time4.getNextTimer(time4);
    System.out.println(time5.getFormattedTime(time5));

    System.out.println(time1.getFormattedTime(time1)+"0");
    timerlist1.add(time1);
    System.out.println(time1.getFormattedTime(time1)+"a");
    timerlist1.add(time2);
    System.out.println(time2.getFormattedTime(time2));
    timerlist1.add(time3);
    System.out.println(time3.getFormattedTime(time3));
    timerlist1.add(time4);
    System.out.println(time4.getFormattedTime(time4));
    timerlist1.add(time5);
    System.out.println(time5.getFormattedTime(time5));