System.out.println(str_pad("coca cola 100", 10, "-", "STR_PAD_RIGHT"));
System.out.println(str_pad("coca cola", 10, "-",  "STR_PAD_RIGHT"));
System.out.println(str_pad("cocacola", 10, "-",   "STR_PAD_RIGHT"));
System.out.println(str_pad("cocacola", 10, "-",   "STR_PAD_LEFT"));
System.out.println(str_pad("cocacola", 10, "-",   "STR_PAD_BOTH"));
System.out.println(str_pad("cocacola", 15, "##",  "STR_PAD_RIGHT"));
System.out.println(str_pad("cocacola", 15, "##",  "STR_PAD_LEFT"));
System.out.println(str_pad("cocacola", 15, "##",  "STR_PAD_BOTH"));
System.out.println(str_pad("cocacola", 15, "&&&", "STR_PAD_RIGHT"));
System.out.println(str_pad("cocacola", 15, "&&&", "STR_PAD_LEFT"));
System.out.println(str_pad("cocacola", 15, "&&&", "STR_PAD_BOTH"));
System.out.println(str_pad("cocacola", 20, "***", "STR_PAD_BOTH"));
System.out.println(str_pad("cocacola", 20, "*-*", "STR_PAD_BOTH"));
System.out.println(str_pad("cocacola_light_taste_is_not_like_original", 20, ":::", "STR_PAD_BOTH"));