if (!results.getString("level").isEmpty()) {                
    .......
   } else if (!results.getString("thesisTitle").isEmpty() ||
          !results.getString("thesisAdvisor").isEmpty()) {  
   ..........
   } else if (!results.getString("company").isEmpty()) {     
   ............