HashMap<Integer, String> FiftyStates = new HashMap <Integer, String>();
FiftyStates.put(1,"Delaware");
FiftyStates.put(2,"Pennsylvania");
...
...
...
...
FiftyStates.put(49,"Alaska");
FiftyStates.put(50,"Hawaii");
Scanner scan = new Scanner(System.in);
System.out.Println(FiftyStates.get(scan.nextInt()));