String createAccount ="CREATE TABLE IF NOT EXISTS`asms`.`customerAccount` ( "
        + " `trn_id` INT NOT NULL AUTO_INCREMENT, "
        + " `trn_date` DATE NOT NULL, "
        + " `narration` VARCHAR(200) NULL, "
        + " `value_date` VARCHAR(50) NULL, "
        + " `debit` DOUBLE NULL,  `credit` DOUBLE NULL,"
        + "  `ledger_balance` DOUBLE NULL DEFAULT 0.0, "
        + " `credit_account_no` VARCHAR(50) NULL, "
        + " `customerAccountcol` VARCHAR(100)NULL, "
        + " `tra_ref_number` VARCHAR(50) NULL, "
        + " `trn_type` VARCHAR(10) NULL, "
        + " `action_type` VARCHAR(10) NULL,  "
        + "`approve_insu_funds` VARCHAR(10) NULL,"
        + "  PRIMARY KEY (`trn_id`), "
        + " UNIQUE INDEX `debit_UNIQUE` (`debit` ASC),"
        + "  UNIQUE INDEX `credit_UNIQUE` (`credit` ASC),"
        + "  UNIQUE INDEX `ledger_balance_UNIQUE` (`ledger_balance` ASC))ENGINE = InnoDB AUTO_INCREMENT = 00001";