class BattleInteractionMachine {
    // ...
    void somemethod() {
        // ...
        SimpleCommand command = new SimpleCommand() {
            // methods here
        }
        // ...
    }
    // ...
}