BEGIN  
  DECLARE OUTVAR VARCHAR(255);
          RETVAR INTEGER;    
  BEGIN
     RETVAR:= ADMIN.GETDATA('A','B','C', OUTVAR);
     DBMS_OUTPUT.PUT_LINE(OUTVAR);     
     DBMS_OUTPUT.PUT_LINE(RETVAR);         
  END;  
END;