private static void init() {
        zipRegexps.put("GB", "GIR[ ]?0AA|((AB|AL|B|BA|BB|BD|BH|BL|BN|BR|BS|BT|CA|CB|CF|CH|CM|CO|CR|CT|CV|CW|DA|DD|DE|DG|DH|DL|DN|DT|DY|E|EC|EH|EN|EX|FK|FY|G|GL|GY|GU|HA|HD|HG|HP|HR|HS|HU|HX|IG|IM|IP|IV|JE|KA|KT|KW|KY|L|LA|LD|LE|LL|LN|LS|LU|M|ME|MK|ML|N|NE|NG|NN|NP|NR|NW|OL|OX|PA|PE|PH|PL|PO|PR|RG|RH|RM|S|SA|SE|SG|SK|SL|SM|SN|SO|SP|SR|SS|ST|SW|SY|TA|TD|TF|TN|TQ|TR|TS|TW|UB|W|WA|WC|WD|WF|WN|WR|WS|WV|YO|ZE)(\\d[\\dA-Z]?[ ]?\\d[ABD-HJLN-UW-Z]{2}))|BFPO[ ]?\\d{1,4}");
        zipRegexps.put("JE", "JE\\d[\\dA-Z]?[ ]?\\d[ABD-HJLN-UW-Z]{2}");
        zipRegexps.put("GG", "GY\\d[\\dA-Z]?[ ]?\\d[ABD-HJLN-UW-Z]{2}");
        zipRegexps.put("IM", "IM\\d[\\dA-Z]?[ ]?\\d[ABD-HJLN-UW-Z]{2}");
        zipRegexps.put("US", "\\d{5}([ \\-]\\d{4})?");
        zipRegexps.put("CA", "[ABCEGHJKLMNPRSTVXY]\\d[ABCEGHJ-NPRSTV-Z][ ]?\\d[ABCEGHJ-NPRSTV-Z]\\d");
        zipRegexps.put("DE", "\\d{5}");
        zipRegexps.put("JP", "\\d{3}-\\d{4}");
        zipRegexps.put("FR", "\\d{2}[ ]?\\d{3}");
        zipRegexps.put("AU", "\\d{4}");
        zipRegexps.put("IT", "\\d{5}");
        zipRegexps.put("CH", "\\d{4}");
        zipRegexps.put("AT", "\\d{4}");
        zipRegexps.put("ES", "\\d{5}");
        zipRegexps.put("NL", "\\d{4}[ ]?[A-Z]{2}");
        zipRegexps.put("BE", "\\d{4}");
        zipRegexps.put("DK", "\\d{4}");
        zipRegexps.put("SE", "\\d{3}[ ]?\\d{2}");
        zipRegexps.put("NO", "\\d{4}");
        zipRegexps.put("BR", "\\d{5}[\\-]?\\d{3}");
        zipRegexps.put("PT", "\\d{4}([\\-]\\d{3})?");
        zipRegexps.put("FI", "\\d{5}");
        zipRegexps.put("AX", "22\\d{3}");
        zipRegexps.put("KR", "\\d{3}[\\-]\\d{3}");
        zipRegexps.put("CN", "\\d{6}");
        zipRegexps.put("TW", "\\d{3}(\\d{2})?");
        zipRegexps.put("SG", "\\d{6}");
        zipRegexps.put("DZ", "\\d{5}");
        zipRegexps.put("AD", "AD\\d{3}");
        zipRegexps.put("AR", "([A-HJ-NP-Z])?\\d{4}([A-Z]{3})?");
        zipRegexps.put("AM", "(37)?\\d{4}");
        zipRegexps.put("AZ", "\\d{4}");
        zipRegexps.put("BH", "((1[0-2]|[2-9])\\d{2})?");
        zipRegexps.put("BD", "\\d{4}");
        zipRegexps.put("BB", "(BB\\d{5})?");
        zipRegexps.put("BY", "\\d{6}");
        zipRegexps.put("BM", "[A-Z]{2}[ ]?[A-Z0-9]{2}");
        zipRegexps.put("BA", "\\d{5}");
        zipRegexps.put("IO", "BBND 1ZZ");
        zipRegexps.put("BN", "[A-Z]{2}[ ]?\\d{4}");
        zipRegexps.put("BG", "\\d{4}");
        zipRegexps.put("KH", "\\d{5}");
        zipRegexps.put("CV", "\\d{4}");
        zipRegexps.put("CL", "\\d{7}");
        zipRegexps.put("CR", "\\d{4,5}|\\d{3}-\\d{4}");
        zipRegexps.put("HR", "\\d{5}");
        zipRegexps.put("CY", "\\d{4}");
        zipRegexps.put("CZ", "\\d{3}[ ]?\\d{2}");
        zipRegexps.put("DO", "\\d{5}");
        zipRegexps.put("EC", "([A-Z]\\d{4}[A-Z]|(?:[A-Z]{2})?\\d{6})?");
        zipRegexps.put("EG", "\\d{5}");
        zipRegexps.put("EE", "\\d{5}");
        zipRegexps.put("FO", "\\d{3}");
        zipRegexps.put("GE", "\\d{4}");
        zipRegexps.put("GR", "\\d{3}[ ]?\\d{2}");
        zipRegexps.put("GL", "39\\d{2}");
        zipRegexps.put("GT", "\\d{5}");
        zipRegexps.put("HT", "\\d{4}");
        zipRegexps.put("HN", "(?:\\d{5})?");
        zipRegexps.put("HU", "\\d{4}");
        zipRegexps.put("IS", "\\d{3}");
        zipRegexps.put("IN", "\\d{6}");
        zipRegexps.put("ID", "\\d{5}");
        zipRegexps.put("IL", "\\d{5}");
        zipRegexps.put("JO", "\\d{5}");
        zipRegexps.put("KZ", "\\d{6}");
        zipRegexps.put("KE", "\\d{5}");
        zipRegexps.put("KW", "\\d{5}");
        zipRegexps.put("LA", "\\d{5}");
        zipRegexps.put("LV", "\\d{4}");
        zipRegexps.put("LB", "(\\d{4}([ ]?\\d{4})?)?");
        zipRegexps.put("LI", "(948[5-9])|(949[0-7])");
        zipRegexps.put("LT", "\\d{5}");
        zipRegexps.put("LU", "\\d{4}");
        zipRegexps.put("MK", "\\d{4}");
        zipRegexps.put("MY", "\\d{5}");
        zipRegexps.put("MV", "\\d{5}");
        zipRegexps.put("MT", "[A-Z]{3}[ ]?\\d{2,4}");
        zipRegexps.put("MU", "(\\d{3}[A-Z]{2}\\d{3})?");
        zipRegexps.put("MX", "\\d{5}");
        zipRegexps.put("MD", "\\d{4}");
        zipRegexps.put("MC", "980\\d{2}");
        zipRegexps.put("MA", "\\d{5}");
        zipRegexps.put("NP", "\\d{5}");
        zipRegexps.put("NZ", "\\d{4}");
        zipRegexps.put("NI", "((\\d{4}-)?\\d{3}-\\d{3}(-\\d{1})?)?");
        zipRegexps.put("NG", "(\\d{6})?");
        zipRegexps.put("OM", "(PC )?\\d{3}");
        zipRegexps.put("PK", "\\d{5}");
        zipRegexps.put("PY", "\\d{4}");
        zipRegexps.put("PH", "\\d{4}");
        zipRegexps.put("PL", "\\d{2}-\\d{3}");
        zipRegexps.put("PR", "00[679]\\d{2}([ \\-]\\d{4})?");
        zipRegexps.put("RO", "\\d{6}");
        zipRegexps.put("RU", "\\d{6}");
        zipRegexps.put("SM", "4789\\d");
        zipRegexps.put("SA", "\\d{5}");
        zipRegexps.put("SN", "\\d{5}");
        zipRegexps.put("SK", "\\d{3}[ ]?\\d{2}");
        zipRegexps.put("SI", "\\d{4}");
        zipRegexps.put("ZA", "\\d{4}");
        zipRegexps.put("LK", "\\d{5}");
        zipRegexps.put("TJ", "\\d{6}");
        zipRegexps.put("TH", "\\d{5}");
        zipRegexps.put("TN", "\\d{4}");
        zipRegexps.put("TR", "\\d{5}");
        zipRegexps.put("TM", "\\d{6}");
        zipRegexps.put("UA", "\\d{5}");
        zipRegexps.put("UY", "\\d{5}");
        zipRegexps.put("UZ", "\\d{6}");
        zipRegexps.put("VA", "00120");
        zipRegexps.put("VE", "\\d{4}");
        zipRegexps.put("ZM", "\\d{5}");
        zipRegexps.put("AS", "96799");
        zipRegexps.put("CC", "6799");
        zipRegexps.put("CK", "\\d{4}");
        zipRegexps.put("RS", "\\d{6}");
        zipRegexps.put("ME", "8\\d{4}");
        zipRegexps.put("CS", "\\d{5}");
        zipRegexps.put("YU", "\\d{5}");
        zipRegexps.put("CX", "6798");
        zipRegexps.put("ET", "\\d{4}");
        zipRegexps.put("FK", "FIQQ 1ZZ");
        zipRegexps.put("NF", "2899");
        zipRegexps.put("FM", "(9694[1-4])([ \\-]\\d{4})?");
        zipRegexps.put("GF", "9[78]3\\d{2}");
        zipRegexps.put("GN", "\\d{3}");
        zipRegexps.put("GP", "9[78][01]\\d{2}");
        zipRegexps.put("GS", "SIQQ 1ZZ");
        zipRegexps.put("GU", "969[123]\\d([ \\-]\\d{4})?");
        zipRegexps.put("GW", "\\d{4}");
        zipRegexps.put("HM", "\\d{4}");
        zipRegexps.put("IQ", "\\d{5}");
        zipRegexps.put("KG", "\\d{6}");
        zipRegexps.put("LR", "\\d{4}");
        zipRegexps.put("LS", "\\d{3}");
        zipRegexps.put("MG", "\\d{3}");
        zipRegexps.put("MH", "969[67]\\d([ \\-]\\d{4})?");
        zipRegexps.put("MN", "\\d{6}");
        zipRegexps.put("MP", "9695[012]([ \\-]\\d{4})?");
        zipRegexps.put("MQ", "9[78]2\\d{2}");
        zipRegexps.put("NC", "988\\d{2}");
        zipRegexps.put("NE", "\\d{4}");
        zipRegexps.put("VI", "008(([0-4]\\d)|(5[01]))([ \\-]\\d{4})?");
        zipRegexps.put("PF", "987\\d{2}");
        zipRegexps.put("PG", "\\d{3}");
        zipRegexps.put("PM", "9[78]5\\d{2}");
        zipRegexps.put("PN", "PCRN 1ZZ");
        zipRegexps.put("PW", "96940");
        zipRegexps.put("RE", "9[78]4\\d{2}");
        zipRegexps.put("SH", "(ASCN|STHL) 1ZZ");
        zipRegexps.put("SJ", "\\d{4}");
        zipRegexps.put("SO", "\\d{5}");
        zipRegexps.put("SZ", "[HLMS]\\d{3}");
        zipRegexps.put("TC", "TKCA 1ZZ");
        zipRegexps.put("WF", "986\\d{2}");
        zipRegexps.put("XK", "\\d{5}");
        zipRegexps.put("YT", "976\\d{2}");

        addressKeywords.add("blvd");
        addressKeywords.add("st");
        addressKeywords.add("street");
        addressKeywords.add("lane");
    }