public class OtherClass {
        ....
        public static void main(String[] args) {
            ...
            Dictionary.main(args);  // ... or provide a different argument list
            ...
        }
    }