public class Example extends javax.swing.JFrame
{
    public Example()
    {
        initComponents(); // This is generated by NB - do NOT remove!

        addListeners(); // add listeners here
    }


    /**
     * Adds listeners to the frame
     */ 
    private void addListeners()
    {
        // Add your listeners here as usual
        this.addWindowListener(new WindowListener()
        {
            @Override
            public void windowOpened(WindowEvent e)
            {
                /* ... */
            }

            /* Other methods of WindowListener ... */
        });
    }

    /* ... */
}