public class <Controller name> implements javafx.fxml.Initializable { // necessary
    ...
    private TextInputControl[] textControls;
    @FXML private TextField profileNameField;
    ...
    public void initialize(URL url, ResourceBundle resourceBundle) {
        textControls = {
                profileNameField,
                ...
        };
        ...
    }
    ...
}