loop: while (goodTotal > 0 && monTotal > 0) {
    // ...
    switch (input) {
        case 'f':
            // ...
            break loop;
        case 'r':
            // ...
            break loop;
        // ...
    }
    // ...
}