protected void doPost(HttpServletRequest request, HttpServletResponse response)
    throws ServletException, IOException {
    //...
    Teacher teacher = new Teacher();
    //...
    request.getSession().setAttribute("teacher", teacher);
    //...
}