public class Users {
    ...

    public static void write(UserObj u, InputStream input, OutputStream output) {
        ...
        String gather = read(input);
        ...
        writer = new PrintWriter(output);
        ...
    }

    public static String read(InputStream input) {
        ...
        read = new Scanner(input);
        ...
    }

    public static UserObj search(String s, InputStream input) {
       ...
       read = new Scanner(input);
       ...
    }

    public static void remove(UserObj u, InputStream input, OutputStream output) {
       ...
       read = new Scanner(input);
       ...
       writer = new PrintWriter(output);
       ...
    }

    public static void update(UserObj u, InputStream input, OutputStream output) {
        remove(u, input, output);
        write(u, input, output);
    }
}

// Client code example
FileInputStream input = new FileInputStream("usersFile.txt");
FileOutputStream output = new FileOutputStream("usersFile.txt");
...
Users.write(myUser, input, output);
...
String result = Users.read(input);
...
myUser = Users.search(myString, input);
...
Users.remove(myUser, input, output);
...
Users.update(myUser, input, output);

// Testing code example
StringBufferInputStream input = new StringBufferInputStream("...");
ByteArrayOutputStream output = new ByteArrayOutputStream();
...
Users.write(myUser, input, output);
...
String result = Users.read(input);
...
myUser = Users.search(myString, input);
...
Users.remove(myUser, input, output);
...
Users.update(myUser, input, output);
...
result = output.toString("UTF-8"); // see docs for other legal charset names