chathistorylist = chatrealm.where(Chat_history_pojo.class)
                     .beginGroup()
                     .equalTo("senderid", Session.getUserID(getApplicationContext()))
                     .equalTo("receiverid", getIntent().getStringExtra("rid"))
                     .endGroup()
                     .or()
                     .beginGroup()
                     .equalTo("receiverid", Session.getUserID(getApplicationContext()))
                     .equalTo("senderid", getIntent().getStringExtra("rid"))
                     .endGroup()
                     .findAll();