String str = "{CDG: {\n"
                + "id: \"32569\",\n"
                + "airport_name: \"Charles De Gaulle\",\n"
                + "latitude: \"49.0167\",\n"
                + "longitude: \"2.55\",\n"
                + "timezone: \"2\",\n"
                + "dst_indicator: \"E\",\n"
                + "city: \"Paris\",\n"
                + "country: \"France\",\n"
                + "country_code: \"FR\",\n"
                + "region: \"TC1\",\n"
                + "listing_display: \"true\",\n"
                + "pseudonyms: \"\"\n"
                + "},\n"
                + "ORY: {\n"
                + "id: \"33539\",\n"
                + "airport_name: \"Orly\",\n"
                + "latitude: \"48.7167\",\n"
                + "longitude: \"2.3833\",\n"
                + "timezone: \"2\",\n"
                + "dst_indicator: \"E\",\n"
                + "city: \"Paris\",\n"
                + "country: \"France\",\n"
                + "country_code: \"FR\",\n"
                + "region: \"TC1\",\n"
                + "listing_display: \"true\",\n"
                + "pseudonyms: \"\"\n"
                + "},\n"
                + "LBG: {\n"
                + "id: \"123425\",\n"
                + "airport_name: \"Le Bourget\",\n"
                + "latitude: \"48.969444\",\n"
                + "longitude: \"2.441389\",\n"
                + "timezone: \"1\",\n"
                + "dst_indicator: \"E\",\n"
                + "city: \"Paris\",\n"
                + "country: \"France\",\n"
                + "country_code: \"FR\",\n"
                + "region: \"TC1\",\n"
                + "listing_display: \"true\",\n"
                + "pseudonyms: \"\"\n"
                + "}}";