alter table table2 
    drop constraint FKCB773E242504FFD6;

drop table table1 if exists;

drop table table2 if exists;

create table table1 (
    ID integer generated by default as identity,
    primary key (ID)
);

create table table2 (
    TABLE1_ID integer not null,
    DATA_1 varchar(128),
    TABLE2_ID varchar(32) not null,
    primary key (TABLE1_ID, TABLE2_ID)
);

alter table table2 
    add constraint FKCB773E242504FFD6 
    foreign key (TABLE1_ID) 
    references table1;