private void complexCode(Collection<Coordinates> collection, ToIntFunction<Coordinates> axisAccessor) {
   // ...
   for (Coordinates c : collection) {
       int axis = axisAccessor.applyAsInt(c);
       //...
   }
   // ...
}