Flux.just("alpha", "beta", "charlie")
        .map(String::toUpperCase)
        .flatMap(s -> Flux.fromArray(s.split("")))
        .groupBy(String::toString)
        .sort((o1,o2) -> o1.key().compareTo(o2.key()))
        .flatMap(group -> Mono.just(Tuples.of(group.key(), group.count().block()))) 
        .map(keyAndCount -> keyAndCount.getT1() + " => " + keyAndCount.getT2() + "; ")