private static GLFWWindowSizeCallback sizeCallback;

//...

public static void setFullScreen(boolean fullScreen) {
    //...
    sizeCallback = GLFWWindowSizeCallback(new SAM() {
        //...
    };
    glfwSetCallback(display, sizeCallback);
    //...
}