SimpleJdbcCall jdbcCall = new SimpleJdbcCall(jdbcTemplate)
            .withProcedureName("spcon_sesion")
            .withoutProcedureColumnMetaDataAccess()
            .declareParameters(new SqlParameter("in_usuario", Types.CHAR))
            .declareParameters(new SqlParameter("in_contrasena", Types.CHAR))
            .declareParameters(new SqlParameter("in_idSistema", Types.INTEGER))
            .declareParameters(new SqlOutParameter("out_idUsuario", Types.INTEGER))
            .declareParameters(new SqlOutParameter("out_nombre", Types.CHAR))
            .declareParameters(new SqlOutParameter("out_paterno", Types.CHAR))
            .declareParameters(new SqlOutParameter("out_materno", Types.CHAR))
            .declareParameters(new SqlOutParameter("out_idPerfil", Types.INTEGER))
            .declareParameters(new SqlOutParameter("out_nombrePerfil", Types.CHAR))
            .declareParameters(new SqlOutParameter("out_idComercio", Types.INTEGER))
            .declareParameters(new SqlOutParameter("out_nombreComercio", Types.CHAR))
            .declareParameters(new SqlOutParameter("out_idTerminal", Types.INTEGER))
            .declareParameters(new SqlOutParameter("out_nombreTerminal", Types.CHAR))
            .declareParameters(new SqlOutParameter("out_idSucursal", Types.INTEGER))
            .declareParameters(new SqlOutParameter("out_referenciaRetiroEfectivo", Types.CHAR))
            .declareParameters(new SqlOutParameter("out_idProveedorSucursal", Types.INTEGER))
            .declareParameters(new SqlOutParameter("out_codigo", Types.CHAR))
            .declareParameters(new SqlOutParameter("out_mensaje", Types.CHAR));