@Component
public class DataGenerator {

    @Value("${spring.jpa.hibernate.ddl-auto}")
    private String schemaDllHandling;

    @Value("${db.autogenerate_data}")
    private Boolean isAutogenerateData;

    public void run(ConfigurableApplicationContext ctx) {

        if (isAutogenerateData == null || !isAutogenerateData || !"create".equalsIgnoreCase(schemaDllHandling)) {
            return; // Do nothing
        }

        System.out.println("Running Bootstrap:");
        ctx.getBean(CountryBootstrap.class).run();
        System.out.println("Bootstrap finished!");
    }
}