...
final TextField textField = new TextField(writer, rectangle, fieldname);
textField.setBorderColor(BaseColor.BLACK);
...
RadioCheckField checkbox = new RadioCheckField(writer, rect, name, "Yes");
checkbox.setBorderColor(BaseColor.BLACK);
...