create.select(sum(decode().when(vvs.VVS_ZWS_ID.eq(47),deck.DEC_BRUTTOPRAEMIE_100)
                                    .otherwise(deck.DEC_BRUTTOPRAEMIE_FOLGE)))
      .from(deck)
      .join(vvs)
        .on(deck.DEC_VER_NUMMER.eq(vvs.VVS_VER_NUMMER))
        .and(deck.DEC_VVS_NUMMER.eq(vvs.VVS_NUMMER))
      .join(agv)
        .on(agv.AGV_CODE.eq(vvs.VVS_AGV_CODE))
      .leftOuterJoin(agd)
        .on(agd.AGD_CODE.eq(deck.DEC_AGD_CODE))
      .where(vvs.VVS_VER_NUMMER.eq(verNummer))
      .and(vvs.VVS_NUMMER.eq(vvsNummer))
      .and(deck.DEC_TBL_CODE.eq("KH"))
      .and(nvl(agv.AGV_AENDERUNGSTYP, "NULL")
        .in("4", "5")
        .or(nvl(agd.AGD_AENDERUNGSTYP, "NULL")
        .notIn("4", "5")))
      .fetch();