@Override
public void onBindViewHolder(@NonNull RecyclerView.ViewHolder holder, int position) {
    // ...
        ((tidurViewHolder) holder).bind(storyList.get(position));
    // ...
        ((yukulViewHolder) holder).bind(yukulList.get(position));
    // ...
        ((homeViewHolder) holder).bind(homeList.get(position));
    // ...
}