List<WebElement> li = driver.findElements(By.name(Constant.YHTY_Commission_upRebate));
            li.get(1).sendKeys(dealerAmountList2);
            System.out.println("INSERT 上2级代理佣金 :  " + dealerAmountList2);
            Log.info("INSERT 上2级代理佣金 :  " + dealerAmountList2);
            li.get(2).sendKeys(dealerAmountList3);
            System.out.println("INSERT 上2级代理佣金 :   " + dealerAmountList3);
            Log.info("INSERT 上2级代理佣金 :  " + dealerAmountList3);
            li.get(3).sendKeys(dealerAmountList4);
            System.out.println("INSERT 上2级代理佣金 :  " + dealerAmountList4);
            Log.info("INSERT 上2级代理佣金 :  " + dealerAmountList4);