-- You cannot really avoid this redundancy
CREATE TYPE STAFF AS OBJECT
(
    STAFF_ID             NUMBER(5),
    STAFF_FIRST_NAME     VARCHAR2(10 BYTE)        NOT NULL,
    STAFF_LAST_NAME      VARCHAR2(20 BYTE)        NOT NULL,
    STAFF_ROLE           VARCHAR2(20 BYTE)        NOT NULL,
    STAFF_OTHER_DETAILS  VARCHAR2(50 BYTE)
);
CREATE TYPE STAFF_TABLE AS TABLE OF STAFF;