@Bean
MessageProducerSupport mqttInbound() {
   ...
   adapter.setOutputChannelName("mainMessageChannel");
   ...
}

@Bean
MessageProducerSupport testInbound() {
   ...
   adapter.setOutputChannelName("mainMessageChannel");
   ...
}