ClientProxyFactoryBean factory = new JaxWsProxyFactoryBean();
factory.setServiceClass(singz.ws.cxf.sample.SampleServiceInterface.class);
factory.setAddress("http://xxx.xxx.com/services/SampleService/v1");
        SampleServiceInterface serviceClient = (SampleServiceInterface) factory.create();
        Client proxy = ClientProxy.getClient(serviceClient);
        List<Header> headersList = new ArrayList<Header>();
        Header testSoapHeader1 = new Header(new QName("uri:singz.ws.sample", "soapheader1"), "SOAP Header Message 1", new JAXBDataBinding(String.class));
        Header testSoapHeader2 = new Header(new QName("uri:singz.ws.sample", "soapheader2"), "SOAP Header Message 2", new JAXBDataBinding(String.class));
        headersList.add(testSoapHeader1);
        headersList.add(testSoapHeader2);
        proxy.getRequestContext().put(Header.HEADER_LIST, headersList);