package quicktest;

public class ChaosLayout extends javax.swing.JPanel {

   /**
    * Creates new form ChaosLayout
    */
   public ChaosLayout() {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings( "unchecked" )
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {

      launch = new javax.swing.JButton();
      chaos = new javax.swing.JButton();
      trials = new javax.swing.JButton();
      map = new javax.swing.JButton();
      start = new javax.swing.JButton();

      launch.setText("Launch");

      chaos.setText("Chaos");

      trials.setText("Trials");

      map.setText("Map");

      start.setText("Start");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(55, 55, 55)
            .addComponent(trials)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
               .addComponent(launch)
               .addComponent(chaos)
               .addComponent(start))
            .addGap(18, 18, 18)
            .addComponent(map)
            .addContainerGap(99, Short.MAX_VALUE))
      );

      layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {chaos, launch, map, start, trials});

      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(launch)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(chaos)
               .addComponent(trials)
               .addComponent(map))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
            .addComponent(start)
            .addContainerGap())
      );
   }// </editor-fold>                        


   // Variables declaration - do not modify                     
   private javax.swing.JButton chaos;
   private javax.swing.JButton launch;
   private javax.swing.JButton map;
   private javax.swing.JButton start;
   private javax.swing.JButton trials;
   // End of variables declaration                   
}