{
        "_rallyAPIMajor": "2",
        "_rallyAPIMinor": "0",
        "_ref": "https://rally1.rallydev.com/slm/webservice/v2.0/attributedefinition/-12507",
        "_objectVersion": "1",
        "_refObjectName": "State",
        "CreationDate": "2006-02-11T12:29:05.000Z",
        "_CreatedAt": "Feb 11, 2006",
        "ObjectID": -12507,
        "Subscription": {...},
        "Workspace": null,
        "AllowedQueryOperators": {...},
        "AllowedValueType": null,
        "AllowedValues": {
          "_rallyAPIMajor": "2",
          "_rallyAPIMinor": "0",
          "_ref": "https://rally1.rallydev.com/slm/webservice/v2.0/AttributeDefinition/-12507/AllowedValues",
          "_type": "AllowedAttributeValue",
          "Count": 4
        },
        "AttributeType": "RATING",
        "Constrained": true,
        "Custom": false,
        "ElementName": "State",
        "Filterable": true,
        "Hidden": false,
        "MaxFractionalDigits": -1,
        "MaxLength": 128,
        "Name": "State",
        "Note": "State of the defect",
        "Owned": true,
        "ReadOnly": false,
        "Required": true,
        "SystemRequired": true,
        "Type": "string",
        "VisibleOnlyToAdmins": false,
        "_type": "AttributeDefinition"
      }