for (int i = 0; i < InformeAmenazasAGR.size()-1; i++) {
              ...
                        InformeSalvaguardasAGR.add(salvaguardaExtraida);

                ...                           
            }