<plugin>
  <groupId>org.glassfish.maven.plugin</groupId>
  <artifactId>maven-glassfish-plugin</artifactId>
  <version>2.2-SNAPSHOT</version>
  <configuration>
    <glassfishDirectory>${glassfish.home}</glassfishDirectory>
    <user>${domain.username}</user>
    <adminPassword>${domain.password}</adminPassword>
    <!-- <passwordFile>path/to/asadmin/passfile</passwordFile> -->
    <autoCreate>true</autoCreate>
    <debug>true</debug>
    <echo>true</echo>
    <skip>${test.int.skip}</skip>
    <domain>
      <name>${project.artifactId}</name>
      <httpPort>8080</httpPort>
      <adminPort>4848</adminPort>
    </domain>
    <components>
      <component>
        <name>${project.artifactId}</name>
        <artifact>${project.build.directory}/${project.build.finalName}.war</artifact>
      </component>
    </components>
  </configuration>
</plugin>