<build>
    <resources>
      <resource>
        <directory>${project.basedir}</directory>
        <includes>
          <include>README.md</include>
        </includes>
        <filtering>true</filtering>
      </resource>
    </resources>
  </build>