public void addMapEntry(String key, String... foods)
{      
       ...
       ...
       favFood = new HashSet<>();
       for (String item : foods) {
            favFood.add(item);
       }
       ...
       ...
}