public class MyModel
{
  // this part is automatically generated by xjc
  @XmlAttribute
  public String foo;

  // you add this with your custom xjc plugin
  @XmlElement(name="foo")
  public String getFooElement() { return foo; }
  public void setFooElement(String newFoo) { foo = newFoo; }
}