List<String> list = Arrays.asList("Actually", "Chalk", "Dramatic", "Fence", "Horrible", "Labored",
                                  "Resonant", "Six", "Slap", "Spark", "Tin", "Treatment");
int idxF = Collections.binarySearch(list, "F");
int idxK = Collections.binarySearch(list, "K");
int idxP = Collections.binarySearch(list, "P");
int idxU = Collections.binarySearch(list, "U");
if (idxF < 0) idxF = ~idxF;
if (idxK < 0) idxK = ~idxK;
if (idxP < 0) idxP = ~idxP;
if (idxU < 0) idxU = ~idxU;
List<String> listA_E = list.subList(0, idxF);
List<String> listF_J = list.subList(idxF, idxK);
List<String> listK_O = list.subList(idxK, idxP);
List<String> listP_T = list.subList(idxP, idxU);
List<String> listU_Z = list.subList(idxU, list.size());
System.out.println(listA_E);
System.out.println(listF_J);
System.out.println(listK_O);
System.out.println(listP_T);
System.out.println(listU_Z);