component = XtextGenerator {
    configuration = {
        project = model.project.StandardProjectConfig {

            baseName = "com.xxx.xxx.dsl.xxx"
            rootPath = ".."
            runtimeTest = {
                enabled = true
            }
            eclipsePlugin = {
                enabled = true
            }
            eclipsePluginTest = {
                enabled = false
            }
            createEclipseMetaData = true
        }
        code = {
            encoding = "UTF-8"
            lineDelimiter = "\r\n"
            fileHeader = "/*\n * generated by Xtext \${version}\n */"
        }
    }
    language = StandardLanguage {
        name = "com.xxx.xxx.xxx.xxx.xxxDSL"
        fileExtensions = "xxx"

        serializer = {
            generateStub = true
        }
        validator = {
            // composedCheck = "org.eclipse.xtext.validation.NamesAreUniqueValidator"
            // Generates checks for @Deprecated grammar annotations, an IssueProvider and a corresponding PropertyPage
            generateDeprecationValidation = true
        }
        junitSupport = {
            junitVersion = "5"
        }
    }