private <T> void myRutine(final Factory<T> factory) {
   // ...
   final T obj = factory.getObj();
   // ...
   final Generics<T> generics = new Generics<>();
   // ...
   generics.put(obj);
   // ...
}