JAXRSServerFactoryBean serverFactory = new JAXRSServerFactoryBean();
serverFactory.setResourceClasses(MessageResource.class);
serverFactory.setResourceProvider(MessageResource.class, new SingletonResourceProvider(new MessageResource()));
serverFactory.setAddress("http://localhost:8080/messenger/");
Map<Object, Object> mappings = new HashMap<Object, Object>(); 
mappings.put("xml", "application/xml"); 
mappings.put("json", "application/json"); 
serverFactory.setExtensionMappings(mappings); 
serverFactory.setProvider(JacksonJsonProvider.class);
serverFactory.create();