SELECT ACCNAME,
CASE WHEN SUM(CREDIT - DEBT) < 0 THEN - SUM(CREDIT - DEBT)
ELSE 0
 END DEBT,
   CASE WHEN SUM(CREDIT - DEBT) > 0 THEN   SUM(CREDIT - DEBT)
        ELSE 0
   END CREDIT
FROM ( ...... ) myTable
GROUP BY ACCNAME ;