CREATE TABLE License
(
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  LicenseNumber VARCHAR(40) NOT NULL UNIQUE
);
CREATE TABLE User
(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  LicenseID INT, 
  CONSTRAINT fk_license_number FOREIGN KEY (LicenseID) REFERENCES License(id)
);