System.out.println("\nDice roll histogram:");
     System.out.println(" 1's: " + nManyStars(numOnes));
     System.out.println(" 2's: " + nManyStars(numTwos));
     System.out.println(" 3's: " + nManyStars(numThrees));
     System.out.println(" 4's: " + nManyStars(numFours));
     System.out.println(" 5's: " + nManyStars(numFives));
     System.out.println(" 6's: " + nManyStars(numSixes));
     System.out.println(" 7's: " + nManyStars(numSevens));
     System.out.println(" 8's: " + nManyStars(numEights));
     System.out.println(" 9's: " + nManyStars(numNines));
     System.out.println("10's: " + nManyStars(numTens));
     System.out.println("11's: " + nManyStars(numElevens));
     System.out.println("12's: " + nManyStars(numTwelves));