CREATE OR REPLACE PROCEDURE OBTENER_ESTADO (RESULTADO OUT SYS_REFCURSOR)
AS
BEGIN
   OPEN RESULTADO FOR 
   SELECT ID, NOMBRE FROM ESTADOS;
EXCEPTION
   WHEN OTHERS
   THEN
      NULL;
END OBTENER_ESTADO;