[
   {
      "sgroup":0,
      "service":0,
      "code":0,
      "value":0,
      "updated_at":0
   },
   {
      "sgroup":1,
      "service":1,
      "code":1,
      "value":1,
      "updated_at":1
   },
   {
      "sgroup":2,
      "service":2,
      "code":2,
      "value":2,
      "updated_at":2
   },
   {
      "sgroup":3,
      "service":3,
      "code":3,
      "value":3,
      "updated_at":3
   },
   {
      "sgroup":4,
      "service":4,
      "code":4,
      "value":4,
      "updated_at":4
   },
   {
      "sgroup":5,
      "service":5,
      "code":5,
      "value":5,
      "updated_at":5
   },
   {
      "sgroup":6,
      "service":6,
      "code":6,
      "value":6,
      "updated_at":6
   },
   {
      "sgroup":7,
      "service":7,
      "code":7,
      "value":7,
      "updated_at":7
   },
   {
      "sgroup":8,
      "service":8,
      "code":8,
      "value":8,
      "updated_at":8
   },
   {
      "sgroup":9,
      "service":9,
      "code":9,
      "value":9,
      "updated_at":9
   },
   {
      "sgroup":10,
      "service":10,
      "code":10,
      "value":10,
      "updated_at":10
   }
]