System.out.print("LOTR characters at the tavern: ");
  System.out.print(Gimli ? "Gimli " : "");
  System.out.print(Boromir ? "Boromir " : "");
  System.out.print(Aragorn ? "Aragorn " : "");
  System.out.print(Sam ? "Sam " : "");
  System.out.print(Legolas ? "Legolas " : "");
  System.out.print(Merry ? "Merry " : "");
  System.out.print(Pippin ? "Pippin " : "");
  System.out.print(Gandalf ? "Gandalf" : "");
  System.out.println();