DAOImpl#performStatements(java.util.Observer observer){
    String stmt;
    ...

    // do insert ...
    observer.update(this, stmt);

    ...
    // do update ...
    observer.update(this, stmt);

    ...
}