List<BandwidthAlertFeedDetailDTO> newFeedDetailsList = new ArrayList<BandwidthAlertFeedDetailDTO>();
...
for loops here {
    ...
    BandwidthAlertFeedDetailDTO some_object_you_want_to_add = feedDetailsList.get(...);
    ...
    newFeedDetailsList.add(some_object_you_want_to_add);
    ...
}