d.findElement(By.id("email")).sendKeys("asd@ymail.com");
WebElement fOne=d.findElement(By.xpath("html/body/div[1]/div/article/div/section[1]/form/div[2]/div[2]/div[1]/input"));
fOne.sendKeys("Studying");
fOne.sendKeys(Keys.TAB);
Sleeper.sleepTightInSeconds(2);
WebElement fTwo=d.findElement(By.xpath("html/body/div[1]/div/article/div/section[1]/form/div[2]/div[2]/div[2]/input"));
fTwo.sendKeys("Engineer/Science MSc");
fTwo.sendKeys(Keys.TAB);
Sleeper.sleepTightInSeconds(2);
WebElement fThree=d.findElement(By.xpath("html/body/div[1]/div/article/div/section[1]/form/div[2]/div[2]/div[3]/input"));
fThree.sendKeys("All India Institute of Medical Sciences (AIIMS), Delhi");
fThree.sendKeys(Keys.TAB);