/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

public final class R {

    // ...

    public static final class id {
        public static final int action0=0x7f0e0090;
        public static final int action_bar=0x7f0e0060;
        public static final int action_bar_activity_content=0x7f0e0000;
        public static final int action_bar_container=0x7f0e005f;
        public static final int action_bar_root=0x7f0e005b;
        public static final int action_bar_spinner=0x7f0e0001;
        public static final int action_bar_subtitle=0x7f0e0041;