SESSION-METATABLE> CREATE TABLE t (id int PRIMARY KEY) ENGINE=INNODB;
SESSION-METATABLE> INSERT INTO t VALUES (1);
SESSION-METATABLE> BEGIN;
SESSION-METATABLE> SELECT id FROM t FOR UPDATE;

SESSION-CONCURRENT> BEGIN;
SESSION-CONCURRENT> SELECT id FROM t FOR UPDATE;
--> HERE SESSION-CONCURRENT is stuck (expected behavior)

SESSION-OBJECT> BEGIN;
SESSION-OBJECT> CREATE TABLE t2 (id int PRIMARY KEY);
--> HERE SESSION-CONCURRENT is not unlock
SESSION-OBJECT> COMMIT;
--> SESSION-CONCURRENT still stuck even after COMMIT;

SESSION-METATABLE>UPDATE t SET id=2 WHERE id=1;
SESSION-METATABLE>COMMIT;
--> HERE SESSION-CONCURRENT is unlock and print
+----+
| id |
+----+
|  2 |
+----+
1 row in set (23.33 sec)