@RunWith(SpringRunner.class)
@AutoConfigureTestDatabase(replace= AutoConfigureTestDatabase.Replace.NONE)
@DataJpaTest
public class DisplayRepositoryTest {

@Autowired
private TestEntityManager testEntityManager;

@Autowired
private DisplayRepository productRespository;

@Before()
public void setUp(){

    Display m = new Display();
    // m.setId(2L); // The ID is autogenerated; can retrieve it from the persistAndFlush result
    m.setCategory("Group1");
    m.setTitle("Product2");

    testEntityManager.persistAndFlush(m);
}

@Test
public void whenFindByName_thenReturnProduct() {
    // when
    Display product = productRespository.findByTitle("Product2").orElseThrow(() -> new RuntimeException("Product not found"));

    // then
    assertThat(product.getTitle()).isEqualTo("Product2");
}

@Test
public void whenFindAll_thenReturnProductList() {
    // when
    List<Display> products = (List<Display>) productRespository.findAll();

    // then
    assertThat(products).hasSize(1);
}
}