public class CipherServer
{
    public static void main(String[] args) throws Exception 
    {
        int port = 7999;
        ServerSocket server = new ServerSocket(port);
        Socket s = server.accept();

        // -Read the key from the file generated by the client.
        ObjectInputStream in = new ObjectInputStream(new FileInputStream("KeyFile.xx"));
        Key key = (Key)in.readObject();
        in.close();

        // -Use the key to decrypt the incoming message from socket s.      
        Cipher cipher = Cipher.getInstance("DES/ECB/PKCS5Padding");
        cipher.init(Cipher.DECRYPT_MODE, key);
        CipherInputStream cipherIn = new CipherInputStream(s.getInputStream(), cipher);

        byte[] array = new byte[44];
        cipherIn.read(array);
        cipherIn.close();
        s.close();

        String message = new String(array);
        System.out.println(message);
    }
}