CREATE TABLE IF NOT EXISTS `entries` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT,
    `item` VARCHAR(255) NOT NULL,
    `dateCreated` TIMESTAMP NOT NULL,
    `lastUpdate` TIMESTAMP NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;