"C:\Program Files\Java\jdk1.6.0_25\include"
"${workspace_loc:/${ProjName}/src/main/c/include}"
"C:\Program Files\Java\jdk1.6.0_25\include\win32"
"C:\data\Projects\java-gtk\gtk3\include\gtk-3.0"
"C:\data\Projects\java-gtk\gtk3\include\glib-2.0"
"C:\data\Projects\java-gtk\gtk3\lib\glib-2.0\include"
"C:\data\Projects\java-gtk\gtk3\include\cairo"
"C:\data\Projects\java-gtk\gtk3\include\pango-1.0"
"C:\data\Projects\java-gtk\gtk3\lib\gtk-3.0\include"
"C:\data\Projects\java-gtk\gtk3\include\gdk-pixbuf-2.0"
"C:\data\Projects\java-gtk\gtk3\include\atk-1.0"