JLabel label1 = new JLabel ("Classrooms");
    j.add(label1,"0, 0");
    JLabel label2 = new JLabel ("This thing");
    j.add(label2,"1, 0");
    JLabel label3 = new JLabel ("That thing");
    j.add(label3,"2, 0");
    JLabel label4 = new JLabel ("Other thing");
    j.add(label4,"3, 0");
    JLabel label5 = new JLabel ("Yeah");
    j.add(label5,"4, 0");