public static void main(String[] args) {
    Scanner scan = new Scanner (System.in);
    double grade;
    String ch;

    do {
        System.out.println("Enter your grade: ");
        grade = scan.nextDouble();
        scan.nextLine(); //Consume the newline character generated by hitting enter

        if (grade <40) {
            System.out.println("you failed");
        }else if (grade >=40 && grade <50) {
            System.out.println("Pass");
        }else if (grade >=50 && grade <60) {
            System.out.println("2:2");
        }else if (grade >=60 && grade <70){
            System.out.println("2:1");
        }else if (grade >=70 && grade <=100){
            System.out.println("1:1");
        }else
            System.out.println("invalid entry");

        System.out.println("Would you like to enter another?");
        ch = scan.nextLine();

    }while(ch.equals("yes")); //Correctly compare strings

    scan.close();
}