String myQuery = ""
+ "SELECT a.symbolname, "
+ "       c.address AS addressdecimal, "
+ "       c.DESCRIPTION, "
+ "       b.constructname, "
+ "       a.declarationtype, "
+ "       a.symbol_id, "
+ "       a.symboltype_id, "
+ "       a.construct_id, "
+ "       a.leaf "
+ "FROM   tblsymboldeclaration a "
+ "       INNER JOIN tbllanguageconstructname b "
+ "         ON a.construct_id = b.construct_id "
+ "       INNER JOIN tblsymbolinstance c "
+ "         ON a.symbol_id = c.symbol_id "
+ "WHERE  a.declarationtype = 1 "
+ "       AND a.ROOT = 1";