SELECT S_NAME FROM TABLE_1 WHERE S_ID = 1
UNION
SELECT I_NAME FROM I_TABLE WHERE I_ID IN (
   SELECT I_ID FROM E_TABLE WHERE S_ID = 1)
UNION
SELECT C_NAME FROM C_TABLE WHERE C_ID IN (
   SELECT C_ID FROM C_TABLE WHERE E_ID IN (
      SELECT E_ID FROM E_TABLE WHERE S_ID = 1))
UNION
SELECT P_NAME FROM P_TABLE WHERE C_ID IN (
   SELECT C_ID FROM C_TABLE WHERE E_ID IN (
      SELECT E_ID FROM E_TABLE WHERE S_ID = 1))
;