db.collection.update(
    {
        $expr:{
            $lt:[
                {
                    $sum:["$total_paid",345]
                },
                "$overall_price"
            ]
        }
    },
    {
        $addToSet:{
            "paid":{
                "price":345,
                "Date": new Date()
            }
        },
        $inc:{
            "total_paid":345
        }
    }
)