PdfPTable table = new PdfPTable(2);
    table.setTotalWidth(200);
    table.setWidths(new int[]{ 1, 10 });
    table.setHorizontalAlignment(Element.ALIGN_LEFT);
    PdfPCell cell;
    cell = new PdfPCell();
    cell.setBorder(PdfPCell.NO_BORDER);
    cell.addElement(new Paragraph("Label"));
    table.addCell(cell);
    cell = new PdfPCell();
    cell.setBorder(PdfPCell.NO_BORDER);
    List list = new List(List.UNORDERED);
    list.add(new ListItem(new Chunk("Value 1")));
    list.add(new ListItem(new Chunk("Value 2")));
    list.add(new ListItem(new Chunk("Value 3")));
    cell.addElement(list);
    table.addCell(cell);