public boolean studentAlreadyExists(String id) throws SQLException{
   connectToDataBase(); 

   selectSQL = "select name from student where idNumber like ?";
   prstmt = con.prepareStatement();
   prstmt.setString(1, id);

   /* Executes the SQL query in this PreparedStatement object and returns the ResultSet object generated by the query.*/
   ResultSet rs = prstmt.executeQuery();
   String dbname = null;
   while(rs.next()){

       dbname = rs.getString("name");
   }

    return dbname != null;
}