<properties>
    <cluster.path.final>${project.build.directory}/${brandingToken}/platform:${project.build.directory}/${brandingToken}/java:...etc</cluster.path.final>
</properties>
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>${software.maven-surefire-plugin}</version>
    <configuration>
        <skipTests>false</skipTests>
        <systemPropertyVariables>
            <branding.token>${brandingToken}</branding.token>
            <cluster.path.final>${cluster.path.final}</cluster.path.final>
        </systemPropertyVariables>
    </configuration>
</plugin>