public static <T> void qqCoisa(List<T> list, Class<String> _string, Class<Integer> _int) throws Exception
{
    ....
    ....

    @SuppressWarnings("unchecked")
    T t = (T) obj;
    list.add(t);

    ....
    ....
}