i1.setEnabled(false);
              i2.setEnabled(false);
              i3.setEnabled(false);
              i4.setEnabled(false);
              i5.setEnabled(false);
              i6.setEnabled(false);
              i7.setEnabled(false);
              i8.setEnabled(false);
              i9.setEnabled(false);