SELECT to_char(PROBING_DATE,'DD-MM-YYYY HH24:MI:SS') AS PROBING_DATE_STR, 
         PROBING_DATE,
         STATUS, 
         SERVICE_NAME 
    FROM TABLE_NAME 
   WHERE PROBING_DATE >= (sysdate-30/1440) 
ORDER BY PROBING_DATE,SERVICE_NAME;